USE BRD_ACT_YMF_COT
GO

DECLARE 
@Data01 date = '2016-08-31 00:00:00.000'
,@Data02 date =  '2016-09-30 00:00:00.000' 
,@Cotista char(15) =  'BRAM0855' 

SELECT PNH.DT_POSICAO DT_MOVIMENTO, 
		 ISNULL( SUM( PNH.VL_CORRIGIDO ), CONVERT( FLOAT, 0 ) ) VL_BRUTO, 
		 ISNULL( SUM( PNH.QT_COTAS ), CONVERT( FLOAT, 0 ) ) QT_COTAS, 
		 ISNULL( PF.VL_COTA_FECHAMENTO, CONVERT( FLOAT, 0 ) ) VL_COTA, 
		 '_A' CD_TIPO,
		 ISNULL( SUM( PNH.VL_IOF ), CONVERT( FLOAT, 0 ) ) VL_IOF, 
		 ISNULL( SUM( PNH.VL_IR ), CONVERT( FLOAT, 0 ) ) VL_IR, 
		 0 ID_NOTA, 
		 PF.CD_FUNDO CD_FUNDO, 
		 CF.NM_ABREVIADO NM_FUNDO, 
		 PNH.CD_COTISTA CD_COTISTA, 
		 CC.NM_CLIENTE NM_COTISTA, 
		 CONVERT( DATETIME, @Data01  ) DT_INICIO, 
		 CONVERT( DATETIME, @Data02  ) DT_FIM,
		 CONVERT( CHAR( 10 ), PNH.DT_POSICAO, 103 ) DS_DT_MOVIMENTO,
       ISNULL( SUM( PNH.VL_RESGATE ), CONVERT( FLOAT, 0 ) ) VL_LIQUIDO,
       CONVERT( DATETIME, NULL ) DT_LIQUIDACAO_FISICA, 
       CONVERT( DATETIME, NULL ) DT_LIQUIDACAO_FINANCEIRA,
       'S' IC_NOME_IMPRESSO,
       CONVERT( CHAR( 005 ), NULL ) CD_TIPO_COLAGEM,
       CONVERT( CHAR( 100 ), NULL ) DS_TIPO_COLAGEM,
       CONVERT( CHAR( 459 ), NULL ) DS_MENSAGEM_EXTRATO,
       CONVERT( CHAR( 050 ), NULL ) DS_TIPO_TRANSFERENCIA,
       CONVERT( CHAR( 050 ), NULL ) DS_HISTORICO  
  FROM COT_POSICAO_NOTA_HISTORICO PNH,   
		 COT_POSICAO_FUNDO PF, 
		 COT_COTISTA C, 
		 COT_CLIENTE CC, 
		 COT_FUNDO F, 
		 COT_CLIENTE CF, 
		 COT_MOVIMENTO M 
 WHERE ( PNH.CD_COTISTA IN (  @Cotista  ) ) AND
       ( PNH.DT_POSICAO = '2016-09-29 00:00:00.000' ) AND
		 ( PNH.ID_NOTA = M.ID_NOTA ) AND
       ( PNH.CD_COTISTA = M.CD_COTISTA ) AND
       ( PNH.CD_FUNDO = M.CD_FUNDO ) AND
		 ( M.DT_LIQUIDACAO_FISICA <= '2016-09-29 00:00:00.000' ) AND
	    ( M.CD_PADRAO <> 'V' ) AND 
       ( PNH.CD_FUNDO = PF.CD_FUNDO ) AND
		 ( PNH.DT_POSICAO = PF.DT_POSICAO ) AND
		 ( PNH.CD_COTISTA = C.CD_COTISTA ) AND
		 ( C.CD_CLIENTE = CC.CD_CLIENTE ) AND
		 ( PNH.CD_FUNDO = F.CD_FUNDO ) AND
		 ( F.CD_CLIENTE = CF.CD_CLIENTE )  AND
	 	 ( EXISTS ( SELECT CD_FUNDO FROM COTV_ACESSO_FUNDO WHERE DS_LOGIN = 'I500422' AND CD_FUNDO = PNH.CD_FUNDO ) )
GROUP BY	PNH.DT_POSICAO, 
			PF.VL_COTA_FECHAMENTO, 
			PF.CD_FUNDO, 
			PNH.CD_COTISTA, 
			CF.NM_ABREVIADO, 
			CC.NM_CLIENTE

UNION ALL 
SELECT RP.DT_POSICAO DT_MOVIMENTO, 
		 ISNULL( SUM( RP.VL_CORRIGIDO ), CONVERT( FLOAT, 0 ) ) VL_BRUTO, 
	    ISNULL( SUM( RP.QT_COTAS ), CONVERT( FLOAT, 0 ) ) QT_COTAS, 
		 ISNULL( PF.VL_COTA_FECHAMENTO, CONVERT( FLOAT, 0 ) ) VL_COTA, 
		 '_A' CD_TIPO,
		 ISNULL( SUM( RP.VL_IOF ), CONVERT( FLOAT, 0 ) ) VL_IOF, 
		 ISNULL( SUM( RP.VL_IR ), CONVERT( FLOAT, 0 ) ) VL_IR, 
		 0 ID_NOTA, 
		 M.CD_FUNDO CD_FUNDO, 
		 CF.NM_ABREVIADO NM_FUNDO, 
		 M.CD_COTISTA CD_COTISTA, 
		 CC.NM_CLIENTE NM_COTISTA, 
		 CONVERT( DATETIME, @Data01  ) DT_INICIO, 
		 CONVERT( DATETIME, @Data02  ) DT_FIM,
		 CONVERT( CHAR( 10 ), RP.DT_POSICAO, 103 ) DS_DT_MOVIMENTO,
       ISNULL( SUM( RP.VL_LIQUIDO_RESGATE ), CONVERT( FLOAT, 0 ) ) VL_LIQUIDO,
       CONVERT( DATETIME, NULL ) DT_LIQUIDACAO_FISICA, 
       CONVERT( DATETIME, NULL ) DT_LIQUIDACAO_FINANCEIRA,
       'S' IC_NOME_IMPRESSO,
       CONVERT( CHAR( 005 ), NULL ) CD_TIPO_COLAGEM,
       CONVERT( CHAR( 100 ), NULL ) DS_TIPO_COLAGEM,
       CONVERT( CHAR( 459 ), NULL ) DS_MENSAGEM_EXTRATO,
       CONVERT( CHAR( 050 ), NULL ) DS_TIPO_TRANSFERENCIA,
       CONVERT( CHAR( 050 ), NULL ) DS_HISTORICO
  FROM COT_RESGATE_PROVISORIO RP, 
		 COT_POSICAO_FUNDO PF, 
		 COT_MOVIMENTO M, 
		 COT_COTISTA C, 
		 COT_CLIENTE CC, 
		 COT_FUNDO F, 
		 COT_CLIENTE CF
 WHERE ( RP.DT_POSICAO = '2016-09-29 00:00:00.000' ) AND
		 ( RP.ID_NOTA = M.ID_NOTA ) AND
		 ( M.CD_COTISTA IN (  @Cotista  ) ) AND
		 ( PF.DT_POSICAO = '2016-09-29 00:00:00.000' ) AND 
		 ( M.DT_LIQUIDACAO_FISICA >= '2016-09-29 00:00:00.000' ) AND
		 ( M.CD_PADRAO <> 'V' ) AND 
		 ( M.CD_FUNDO = PF.CD_FUNDO ) AND
		 ( M.CD_COTISTA = C.CD_COTISTA ) AND
		 ( C.CD_CLIENTE = CC.CD_CLIENTE ) AND
		 ( M.CD_FUNDO = F.CD_FUNDO ) AND
		 ( F.CD_CLIENTE = CF.CD_CLIENTE ) AND
	 	 ( EXISTS ( SELECT CD_FUNDO FROM COTV_ACESSO_FUNDO WHERE DS_LOGIN = 'I500422' AND CD_FUNDO = M.CD_FUNDO ) )
GROUP BY	RP.DT_POSICAO, 
			PF.VL_COTA_FECHAMENTO,
			M.CD_FUNDO, 
			M.CD_COTISTA,
			CF.NM_ABREVIADO,
			CC.NM_CLIENTE

UNION ALL 
SELECT PNH.DT_POSICAO DT_MOVIMENTO,   
		 ISNULL( SUM( PNH.VL_CORRIGIDO ), CONVERT( FLOAT, 0 ) ) VL_BRUTO,   
		 ISNULL( SUM( PNH.QT_COTAS ), CONVERT( FLOAT, 0 ) ) QT_COTAS,   
		 ISNULL( PF.VL_COTA_FECHAMENTO, CONVERT( FLOAT, 0 ) ) VL_COTA, 
		 'XX' CD_TIPO,
		 ISNULL( SUM( PNH.VL_IOF ), CONVERT( FLOAT, 0 ) ) VL_IOF, 
		 ISNULL( SUM( PNH.VL_IR ), CONVERT( FLOAT, 0 ) ) VL_IR, 
		 9999999 ID_NOTA, 
		 PF.CD_FUNDO CD_FUNDO, 
		 CF.NM_ABREVIADO NM_FUNDO, 
		 PNH.CD_COTISTA CD_COTISTA, 
		 CC.NM_CLIENTE NM_COTISTA, 
		 CONVERT( DATETIME, @Data01  ) DT_INICIO, 
		 CONVERT( DATETIME, @Data02  ) DT_FIM,
		 CONVERT( CHAR( 10 ), PNH.DT_POSICAO, 103 ) DS_DT_MOVIMENTO,
       ISNULL( SUM( PNH.VL_RESGATE ), CONVERT( FLOAT, 0 ) ) VL_LIQUIDO,
       CONVERT( DATETIME, NULL ) DT_LIQUIDACAO_FISICA, 
       CONVERT( DATETIME, NULL ) DT_LIQUIDACAO_FINANCEIRA,
       'S' IC_NOME_IMPRESSO,
       CONVERT( CHAR( 005 ), NULL ) CD_TIPO_COLAGEM,
       CONVERT( CHAR( 100 ), NULL ) DS_TIPO_COLAGEM,
       CONVERT( CHAR( 459 ), NULL ) DS_MENSAGEM_EXTRATO,
       CONVERT( CHAR( 050 ), NULL ) DS_TIPO_TRANSFERENCIA,
       CONVERT( CHAR( 050 ), NULL ) DS_HISTORICO
  FROM COT_POSICAO_NOTA_HISTORICO PNH,   
		 COT_POSICAO_FUNDO PF, 
		 COT_COTISTA C, 
		 COT_CLIENTE CC, 
		 COT_FUNDO F, 
		 COT_CLIENTE CF, 
		 COT_MOVIMENTO M 
 WHERE ( PNH.CD_COTISTA IN (  @Cotista  ) ) AND
       ( PNH.DT_POSICAO = ( SELECT MAX( CPF.DT_POSICAO ) 
                              FROM COT_POSICAO_FUNDO CPF
                             WHERE CPF.CD_FUNDO = PF.CD_FUNDO 
                               AND CPF.DT_POSICAO >= @Data01 
                               AND CPF.DT_POSICAO <= @Data02  
                               AND CPF.IC_AF_POSICAO = 'F' ) ) AND			
		 ( PNH.CD_FUNDO = PF.CD_FUNDO ) AND
		 ( PNH.DT_POSICAO = PF.DT_POSICAO ) AND
		 ( PNH.CD_COTISTA = C.CD_COTISTA ) AND
		 ( PNH.ID_NOTA = M.ID_NOTA ) AND
       ( PNH.CD_COTISTA = M.CD_COTISTA ) AND
       ( PNH.CD_FUNDO = M.CD_FUNDO ) AND
	  	 ( M.DT_LIQUIDACAO_FISICA <= PNH.DT_POSICAO ) AND
		 ( M.CD_PADRAO <> 'V' ) AND 
		 ( C.CD_CLIENTE = CC.CD_CLIENTE ) AND
		 ( PNH.CD_FUNDO = F.CD_FUNDO ) AND
		 ( F.CD_CLIENTE = CF.CD_CLIENTE ) AND
	 	 ( EXISTS ( SELECT CD_FUNDO FROM COTV_ACESSO_FUNDO WHERE DS_LOGIN = 'I500422' AND CD_FUNDO = PNH.CD_FUNDO ) )
GROUP BY	PNH.DT_POSICAO, 
			PF.VL_COTA_FECHAMENTO, 
			PF.CD_FUNDO, 
			PNH.CD_COTISTA, 
			CF.NM_ABREVIADO, 
			CC.NM_CLIENTE

UNION ALL 
SELECT RP.DT_POSICAO DT_MOVIMENTO, 
		 ISNULL( SUM( RP.VL_CORRIGIDO ), CONVERT( FLOAT, 0 ) ) VL_BRUTO, 
		 ISNULL( SUM( RP.QT_COTAS ), CONVERT( FLOAT, 0 ) ) QT_COTAS, 
		 ISNULL( PF.VL_COTA_FECHAMENTO, CONVERT( FLOAT, 0 ) ) VL_COTA, 
		 'XX' CD_TIPO,
		 ISNULL( SUM( RP.VL_IOF ), CONVERT( FLOAT, 0 ) ) VL_IOF, 
		 ISNULL( SUM( RP.VL_IR ), CONVERT( FLOAT, 0 ) ) VL_IR, 
		 9999999 ID_NOTA, 
		 M.CD_FUNDO CD_FUNDO, 
		 CF.NM_ABREVIADO NM_FUNDO, 
		 M.CD_COTISTA CD_COTISTA, 
		 CC.NM_CLIENTE NM_COTISTA, 
		 CONVERT( DATETIME, @Data01  ) DT_INICIO, 
		 CONVERT( DATETIME, @Data02  ) DT_FIM,
		 CONVERT( CHAR( 10 ), RP.DT_POSICAO, 103 ) DS_DT_MOVIMENTO,
       ISNULL( SUM( RP.VL_LIQUIDO_RESGATE ), CONVERT( FLOAT, 0 ) ) VL_LIQUIDO,
       CONVERT( DATETIME, NULL ) DT_LIQUIDACAO_FISICA, 
       CONVERT( DATETIME, NULL ) DT_LIQUIDACAO_FINANCEIRA,
       'S' IC_NOME_IMPRESSO,
       CONVERT( CHAR( 005 ), NULL ) CD_TIPO_COLAGEM,
       CONVERT( CHAR( 100 ), NULL ) DS_TIPO_COLAGEM,
       CONVERT( CHAR( 459 ), NULL ) DS_MENSAGEM_EXTRATO,
       CONVERT( CHAR( 050 ), NULL ) DS_TIPO_TRANSFERENCIA,
       CONVERT( CHAR( 050 ), NULL ) DS_HISTORICO
  FROM COT_RESGATE_PROVISORIO RP, 
		 COT_POSICAO_FUNDO PF,
		 COT_MOVIMENTO M, 
		 COT_COTISTA C, 
		 COT_CLIENTE CC, 
		 COT_FUNDO F, 
		 COT_CLIENTE CF
 WHERE ( RP.DT_POSICAO = ( SELECT MAX( CPF.DT_POSICAO ) 
                             FROM COT_POSICAO_FUNDO CPF
                            WHERE CPF.CD_FUNDO = PF.CD_FUNDO 
                              AND CPF.DT_POSICAO >= @Data01  
                              AND CPF.DT_POSICAO <= @Data02  
                              AND CPF.IC_AF_POSICAO = 'F' ) ) AND
		 ( RP.ID_NOTA_APLICACAO = M.ID_NOTA ) AND
		 ( M.CD_COTISTA IN (  @Cotista  ) ) AND
		 ( PF.DT_POSICAO = RP.DT_POSICAO ) AND  
		 ( M.CD_FUNDO = PF.CD_FUNDO ) AND
		 ( M.DT_LIQUIDACAO_FISICA <= RP.DT_POSICAO ) AND
		 ( M.CD_PADRAO <> 'V' ) AND 
		 ( M.CD_COTISTA = C.CD_COTISTA ) AND
		 ( C.CD_CLIENTE = CC.CD_CLIENTE ) AND
		 ( M.CD_FUNDO = F.CD_FUNDO ) AND
		 ( F.CD_CLIENTE = CF.CD_CLIENTE ) AND
	 	 ( EXISTS ( SELECT CD_FUNDO FROM COTV_ACESSO_FUNDO WHERE DS_LOGIN = 'I500422' AND CD_FUNDO = M.CD_FUNDO ) )
GROUP BY	RP.DT_POSICAO, 
			PF.VL_COTA_FECHAMENTO,
			M.CD_FUNDO, 
			M.CD_COTISTA,
			CF.NM_ABREVIADO,
			CC.NM_CLIENTE