USE BRD_ACT_YMF_COT
GO

DECLARE 
@Data01 date = '2016-08-31 00:00:00.000'
,@Data02 date =  '2016-09-30 00:00:00.000' 
,@Cotista char(15) =  'BRAM0855' 

SELECT M.DT_LIQUIDACAO_FISICA DT_MOVIMENTO,   
		 M.VL_BRUTO VL_BRUTO,   
		 M.QT_COTAS QT_COTAS,   
       CASE RTRIM( M.CD_TIPO ) 
        WHEN 'AG' THEN ISNULL( M.VL_COTA_MOVIMENTACAO, PF.VL_COTA_FECHAMENTO ) 
        ELSE PF.VL_COTA_FECHAMENTO 
       END VL_COTA,
		 M.CD_TIPO CD_TIPO,  
		 M.VL_IOF VL_IOF, 
		 M.VL_IR VL_IR, 
		 M.ID_NOTA ID_NOTA, 
		 M.CD_FUNDO CD_FUNDO, 
		 CF.NM_ABREVIADO NM_FUNDO, 
		 M.CD_COTISTA CD_COTISTA, 
		 CC.NM_CLIENTE NM_COTISTA, 
		 CONVERT( DATETIME, @Data01 ) DT_INICIO, 
		 CONVERT( DATETIME,  @Data02  ) DT_FIM,
		 CONVERT( CHAR( 10 ), M.DT_LIQUIDACAO_FISICA, 103 ) DS_DT_MOVIMENTO,
       M.VL_LIQUIDO VL_LIQUIDO,
       M.DT_LIQUIDACAO_FISICA DT_LIQUIDACAO_FISICA,
       M.DT_LIQUIDACAO_FINANCEIRA DT_LIQUIDACAO_FINANCEIRA, 
       'S' IC_NOME_IMPRESSO,
       M.CD_TIPO_COLAGEM,
       TC.DS_TIPO_COLAGEM,
       CONVERT( CHAR( 459 ), NULL ) DS_MENSAGEM_EXTRATO,
       ISNULL( TT.DS_TIPO_TRANSFERENCIA, '' ) DS_TIPO_TRANSFERENCIA,
       CONVERT( CHAR( 050 ), NULL ) DS_HISTORICO  
  FROM COT_MOVIMENTO M
         INNER JOIN COT_POSICAO_FUNDO PF
           ON M.CD_FUNDO = PF.CD_FUNDO AND
              M.DT_LIQUIDACAO_FISICA = PF.DT_POSICAO 
         LEFT OUTER JOIN COT_TRANSFERENCIA_TIPO TT
            ON M.CD_TIPO_TRANSFERENCIA = TT.CD_TIPO_TRANSFERENCIA
         INNER JOIN COT_FUNDO F
                    INNER JOIN COT_CLIENTE CF
                       ON F.CD_CLIENTE = CF.CD_CLIENTE
           ON M.CD_FUNDO = F.CD_FUNDO
         INNER JOIN COT_COTISTA C
                    INNER JOIN COT_CLIENTE CC 
                       ON C.CD_CLIENTE = CC.CD_CLIENTE
           ON M.CD_COTISTA = C.CD_COTISTA
         LEFT OUTER JOIN COT_MOVIMENTO_TIPO_COLAGEM TC
           ON M.CD_TIPO_COLAGEM = TC.CD_TIPO_COLAGEM
 WHERE ( M.CD_COTISTA IN (  @Cotista  ) ) AND
		 ( M.DT_LIQUIDACAO_FISICA >= @Data01 AND 
         M.DT_LIQUIDACAO_FISICA <= ( SELECT MAX( CPF.DT_POSICAO ) 
                                       FROM COT_POSICAO_FUNDO CPF
                                      WHERE CPF.CD_FUNDO = PF.CD_FUNDO 
                                        AND CPF.DT_POSICAO >= @Data01 
                                        AND CPF.DT_POSICAO <=  @Data02  
                                        AND CPF.IC_AF_POSICAO = 'F' ) ) AND
		 ( RTRIM( M.CD_TIPO ) IN ( 'A', 'AC', 'AG' ) ) AND
		 ( M.CD_PADRAO <> 'V' ) AND 
		 ( M.DT_TRANSFERENCIA IS NULL ) AND
	 	 ( EXISTS ( SELECT CD_FUNDO FROM COTV_ACESSO_FUNDO WHERE DS_LOGIN = 'I500422' AND CD_FUNDO = M.CD_FUNDO ) )

UNION ALL
SELECT M.DT_TRANSFERENCIA DT_MOVIMENTO,   
		 PNH.VL_CORRIGIDO + ( SELECT ISNULL( SUM( R.VL_CORRIGIDO ), 0 ) 
                 				   FROM COT_RESGATE R
                             WHERE M.ID_NOTA = R.ID_NOTA_APLICACAO AND 
                                   M.DT_TRANSFERENCIA = R.DT_RESGATE ) VL_BRUTO,   
		 PNH.QT_COTAS + ( SELECT ISNULL( SUM( R.QT_COTAS ), 0 ) 
                          FROM COT_RESGATE R
                         WHERE M.ID_NOTA = R.ID_NOTA_APLICACAO AND 
							          M.DT_TRANSFERENCIA = R.DT_RESGATE ) QT_COTAS, 
       PNH.VL_COTA_APLICACAO VL_COTA,			
		 'AT' CD_TIPO,  
		 M.VL_IOF VL_IOF, 
	 	 M.VL_IR VL_IR, 
		 M.ID_NOTA ID_NOTA, 
		 M.CD_FUNDO CD_FUNDO, 
		 CF.NM_ABREVIADO NM_FUNDO, 
		 M.CD_COTISTA CD_COTISTA, 
		 CC.NM_CLIENTE NM_COTISTA, 
		 CONVERT( DATETIME, @Data01 ) DT_INICIO, 
		 CONVERT( DATETIME,  @Data02  ) DT_FIM,
		 CONVERT( CHAR( 10 ), M.DT_TRANSFERENCIA, 103 ) DS_DT_MOVIMENTO,
       M.VL_LIQUIDO VL_LIQUIDO,
       M.DT_LIQUIDACAO_FISICA DT_LIQUIDACAO_FISICA,
       M.DT_LIQUIDACAO_FINANCEIRA DT_LIQUIDACAO_FINANCEIRA, 
       'S' IC_NOME_IMPRESSO,
       M.CD_TIPO_COLAGEM,
       TC.DS_TIPO_COLAGEM,
       CONVERT( CHAR( 459 ), NULL ) DS_MENSAGEM_EXTRATO,
       ISNULL( TT.DS_TIPO_TRANSFERENCIA, '' ) DS_TIPO_TRANSFERENCIA,
       CONVERT( CHAR( 050 ), NULL ) DS_HISTORICO  
  FROM COT_MOVIMENTO M
        INNER JOIN COT_POSICAO_NOTA_HISTORICO PNH
            ON M.ID_NOTA = PNH.ID_NOTA AND
               M.DT_TRANSFERENCIA = PNH.DT_POSICAO
         LEFT OUTER JOIN COT_TRANSFERENCIA_TIPO TT
            ON M.CD_TIPO_TRANSFERENCIA = TT.CD_TIPO_TRANSFERENCIA
         INNER JOIN COT_POSICAO_FUNDO PF
           ON M.CD_FUNDO = PF.CD_FUNDO AND
              M.DT_LIQUIDACAO_FISICA = PF.DT_POSICAO 
         INNER JOIN COT_FUNDO F
                    INNER JOIN COT_CLIENTE CF
                       ON F.CD_CLIENTE = CF.CD_CLIENTE
           ON M.CD_FUNDO = F.CD_FUNDO
         INNER JOIN COT_COTISTA C
                    INNER JOIN COT_CLIENTE CC 
                       ON C.CD_CLIENTE = CC.CD_CLIENTE
           ON M.CD_COTISTA = C.CD_COTISTA
         LEFT OUTER JOIN COT_MOVIMENTO_TIPO_COLAGEM TC
           ON M.CD_TIPO_COLAGEM = TC.CD_TIPO_COLAGEM 
 WHERE ( M.CD_COTISTA IN (  @Cotista  ) ) AND
		 ( M.DT_TRANSFERENCIA >= @Data01 AND 
         M.DT_TRANSFERENCIA <= ( SELECT MAX( CPF.DT_POSICAO ) 
                                   FROM COT_POSICAO_FUNDO CPF
                                  WHERE CPF.CD_FUNDO = PF.CD_FUNDO 
                                    AND CPF.DT_POSICAO >= @Data01 
                                    AND CPF.DT_POSICAO <=  @Data02  
                                    AND CPF.IC_AF_POSICAO = 'F' ) ) AND
		 ( RTRIM( M.CD_TIPO ) IN ( 'A', 'AC', 'AG' ) ) AND 
		 ( M.CD_PADRAO <> 'V' ) AND 	
       ( M.DT_TRANSFERENCIA <> M.DT_MOVIMENTO ) AND 	 	   
       ( EXISTS ( SELECT CD_FUNDO FROM COTV_ACESSO_FUNDO WHERE DS_LOGIN = 'I500422' AND CD_FUNDO = M.CD_FUNDO ) )

UNION ALL
SELECT M.DT_TRANSFERENCIA DT_MOVIMENTO,   
		 M.VL_BRUTO VL_BRUTO,   
		 M.QT_COTAS QT_COTAS, 
       CASE RTRIM( M.CD_TIPO ) 
          WHEN 'AG' THEN ISNULL( M.VL_COTA_MOVIMENTACAO, PF.VL_COTA_FECHAMENTO ) 
          ELSE PF.VL_COTA_FECHAMENTO 
       END VL_COTA,
		 'AT' CD_TIPO,  
		 M.VL_IOF VL_IOF, 
		 M.VL_IR VL_IR, 
		 M.ID_NOTA ID_NOTA, 
		 M.CD_FUNDO CD_FUNDO, 
		 CF.NM_ABREVIADO NM_FUNDO, 
		 M.CD_COTISTA CD_COTISTA, 
		 CC.NM_CLIENTE NM_COTISTA, 
		 CONVERT( DATETIME, @Data01 ) DT_INICIO, 
		 CONVERT( DATETIME,  @Data02  ) DT_FIM,
		 CONVERT( CHAR( 10 ), M.DT_TRANSFERENCIA, 103 ) DS_DT_MOVIMENTO,
       M.VL_LIQUIDO VL_LIQUIDO,
       M.DT_LIQUIDACAO_FISICA DT_LIQUIDACAO_FISICA,
       M.DT_LIQUIDACAO_FINANCEIRA DT_LIQUIDACAO_FINANCEIRA, 
       'S' IC_NOME_IMPRESSO,
       M.CD_TIPO_COLAGEM,
       TC.DS_TIPO_COLAGEM,
       CONVERT( CHAR( 459 ), NULL ) DS_MENSAGEM_EXTRATO,
       ISNULL( TT.DS_TIPO_TRANSFERENCIA, '' ) DS_TIPO_TRANSFERENCIA,
       CONVERT( CHAR( 050 ), NULL ) DS_HISTORICO 
  FROM COT_MOVIMENTO M
         INNER JOIN COT_POSICAO_FUNDO PF
           ON M.CD_FUNDO = PF.CD_FUNDO AND
              M.DT_LIQUIDACAO_FISICA = PF.DT_POSICAO 
         LEFT OUTER JOIN COT_TRANSFERENCIA_TIPO TT
            ON M.CD_TIPO_TRANSFERENCIA = TT.CD_TIPO_TRANSFERENCIA
         INNER JOIN COT_FUNDO F
                    INNER JOIN COT_CLIENTE CF
                       ON F.CD_CLIENTE = CF.CD_CLIENTE
           ON M.CD_FUNDO = F.CD_FUNDO
         INNER JOIN COT_COTISTA C
                    INNER JOIN COT_CLIENTE CC 
                       ON C.CD_CLIENTE = CC.CD_CLIENTE
           ON M.CD_COTISTA = C.CD_COTISTA
         LEFT OUTER JOIN COT_MOVIMENTO_TIPO_COLAGEM TC
           ON M.CD_TIPO_COLAGEM = TC.CD_TIPO_COLAGEM
 WHERE ( M.CD_COTISTA IN (  @Cotista  ) ) AND
		 ( M.DT_TRANSFERENCIA >= @Data01 AND 
         M.DT_TRANSFERENCIA <= ( SELECT MAX( CPF.DT_POSICAO ) 
                                   FROM COT_POSICAO_FUNDO CPF
                                  WHERE CPF.CD_FUNDO = PF.CD_FUNDO 
                                    AND CPF.DT_POSICAO >= @Data01 
                                    AND CPF.DT_POSICAO <=  @Data02  
                                    AND CPF.IC_AF_POSICAO = 'F' ) ) AND
		 ( RTRIM( M.CD_TIPO ) IN ( 'A', 'AC', 'AG' ) ) AND 
		 ( M.CD_PADRAO <> 'V' ) AND 
	    ( M.DT_TRANSFERENCIA = M.DT_MOVIMENTO ) AND  
	 	 ( EXISTS ( SELECT CD_FUNDO FROM COTV_ACESSO_FUNDO WHERE DS_LOGIN = 'I500422' AND CD_FUNDO = M.CD_FUNDO ) )

UNION ALL
SELECT M.DT_LIQUIDACAO_FISICA DT_MOVIMENTO,   
		 M.VL_BRUTO VL_BRUTO,   
		 M.QT_COTAS QT_COTAS,   
		 PF.VL_COTA_FECHAMENTO VL_COTA,   
		 M.CD_TIPO CD_TIPO,  
		 M.VL_IOF VL_IOF, 
		 M.VL_IR VL_IR, 
		 M.ID_NOTA ID_NOTA, 
		 M.CD_FUNDO CD_FUNDO, 
		 CF.NM_ABREVIADO NM_FUNDO, 
		 M.CD_COTISTA CD_COTISTA, 
		 CC.NM_CLIENTE NM_COTISTA, 
		 CONVERT( DATETIME, @Data01 ) DT_INICIO, 
		 CONVERT( DATETIME,  @Data02  ) DT_FIM,
		 CONVERT( CHAR( 10 ), M.DT_LIQUIDACAO_FISICA, 103 ) DS_DT_MOVIMENTO,
       M.VL_LIQUIDO VL_LIQUIDO,
       M.DT_LIQUIDACAO_FISICA DT_LIQUIDACAO_FISICA,
       M.DT_LIQUIDACAO_FINANCEIRA DT_LIQUIDACAO_FINANCEIRA, 
       'S' IC_NOME_IMPRESSO,
       M.CD_TIPO_COLAGEM,
       TC.DS_TIPO_COLAGEM,
       CONVERT( CHAR( 459 ), NULL ) DS_MENSAGEM_EXTRATO,
       ISNULL( TT.DS_TIPO_TRANSFERENCIA, '' ) DS_TIPO_TRANSFERENCIA,
       CONVERT( CHAR( 050 ), NULL ) DS_HISTORICO
  FROM COT_MOVIMENTO M
         INNER JOIN COT_POSICAO_FUNDO PF
           ON M.CD_FUNDO = PF.CD_FUNDO AND
              M.DT_LIQUIDACAO_FISICA = PF.DT_POSICAO 
         LEFT OUTER JOIN COT_TRANSFERENCIA_TIPO TT
            ON M.CD_TIPO_TRANSFERENCIA = TT.CD_TIPO_TRANSFERENCIA
         INNER JOIN COT_FUNDO F
                    INNER JOIN COT_CLIENTE CF
                       ON F.CD_CLIENTE = CF.CD_CLIENTE
           ON M.CD_FUNDO = F.CD_FUNDO
         INNER JOIN COT_COTISTA C
                    INNER JOIN COT_CLIENTE CC 
                       ON C.CD_CLIENTE = CC.CD_CLIENTE
           ON M.CD_COTISTA = C.CD_COTISTA
         LEFT OUTER JOIN COT_MOVIMENTO_TIPO_COLAGEM TC
           ON M.CD_TIPO_COLAGEM = TC.CD_TIPO_COLAGEM
 WHERE ( M.CD_COTISTA IN (  @Cotista  ) ) AND
		 ( M.DT_LIQUIDACAO_FISICA >= @Data01 AND 
         M.DT_LIQUIDACAO_FISICA <= ( SELECT MAX( CPF.DT_POSICAO ) 
                                       FROM COT_POSICAO_FUNDO CPF
                                      WHERE CPF.CD_FUNDO = PF.CD_FUNDO 
                                        AND CPF.DT_POSICAO >= @Data01 
                                        AND CPF.DT_POSICAO <=  @Data02  
                                        AND CPF.IC_AF_POSICAO = 'F' ) ) AND
		 ( RTRIM( M.CD_TIPO ) NOT IN ( 'A', 'AC', 'AG' ) ) AND 
		 ( RTRIM( M.CD_TIPO ) <> 'TR' ) AND 
		 ( RTRIM( M.CD_TIPO ) <> 'RM' ) AND 
		 ( M.CD_PADRAO <> 'V' ) AND 
	 	 ( EXISTS ( SELECT CD_FUNDO FROM COTV_ACESSO_FUNDO WHERE DS_LOGIN = 'I500422' AND CD_FUNDO = M.CD_FUNDO ) )
UNION ALL
SELECT M.DT_LIQUIDACAO_FISICA DT_MOVIMENTO,   
		 ( MA.VL_COTA_MOVIMENTACAO * R.QT_COTAS ) VL_BRUTO,   
		 R.QT_COTAS QT_COTAS,   
		 MA.VL_COTA_MOVIMENTACAO VL_COTA,   
		 M.CD_TIPO CD_TIPO,  
		 R.VL_IOF VL_IOF, 
		 R.VL_IR VL_IR, 
		 M.ID_NOTA ID_NOTA, 
		 M.CD_FUNDO CD_FUNDO, 
		 CF.NM_ABREVIADO NM_FUNDO, 
		 M.CD_COTISTA CD_COTISTA, 
		 CC.NM_CLIENTE NM_COTISTA, 
		 CONVERT( DATETIME, @Data01 ) DT_INICIO, 
		 CONVERT( DATETIME,  @Data02  ) DT_FIM,
		 CONVERT( CHAR( 10 ), M.DT_LIQUIDACAO_FISICA, 103 ) DS_DT_MOVIMENTO,
       M.VL_LIQUIDO VL_LIQUIDO,
       M.DT_LIQUIDACAO_FISICA DT_LIQUIDACAO_FISICA,
       M.DT_LIQUIDACAO_FINANCEIRA DT_LIQUIDACAO_FINANCEIRA, 
       'S' IC_NOME_IMPRESSO,
       M.CD_TIPO_COLAGEM,
       TC.DS_TIPO_COLAGEM,
       CONVERT( CHAR( 459 ), NULL ) DS_MENSAGEM_EXTRATO,
       ISNULL( TT.DS_TIPO_TRANSFERENCIA, '' ) DS_TIPO_TRANSFERENCIA,
       CONVERT( CHAR( 050 ), NULL ) DS_HISTORICO 
  FROM COT_MOVIMENTO M 
         INNER JOIN COT_POSICAO_FUNDO PF
           ON M.CD_FUNDO = PF.CD_FUNDO AND
              M.DT_LIQUIDACAO_FISICA = PF.DT_POSICAO 
         LEFT OUTER JOIN COT_TRANSFERENCIA_TIPO TT
            ON M.CD_TIPO_TRANSFERENCIA = TT.CD_TIPO_TRANSFERENCIA
         INNER JOIN COT_FUNDO F
                    INNER JOIN COT_CLIENTE CF
                       ON F.CD_CLIENTE = CF.CD_CLIENTE
           ON M.CD_FUNDO = F.CD_FUNDO
         INNER JOIN COT_COTISTA C
                    INNER JOIN COT_CLIENTE CC 
                       ON C.CD_CLIENTE = CC.CD_CLIENTE
           ON M.CD_COTISTA = C.CD_COTISTA
         INNER JOIN COT_TRANSFERENCIA TR
                    INNER JOIN COT_MOVIMENTO MA
                       ON TR.ID_NOTA_DESTINO = MA.ID_NOTA
           ON M.ID_NOTA = TR.ID_NOTA_RESGATE
         INNER JOIN COT_RESGATE R
           ON M.ID_NOTA = R.ID_NOTA
         LEFT OUTER JOIN COT_MOVIMENTO_TIPO_COLAGEM TC
           ON M.CD_TIPO_COLAGEM = TC.CD_TIPO_COLAGEM
 WHERE ( M.CD_COTISTA IN (  @Cotista  ) ) AND
		 ( M.DT_LIQUIDACAO_FISICA >= @Data01 AND 
         M.DT_LIQUIDACAO_FISICA <= ( SELECT MAX( CPF.DT_POSICAO ) 
                                       FROM COT_POSICAO_FUNDO CPF
                                      WHERE CPF.CD_FUNDO = PF.CD_FUNDO 
                                        AND CPF.DT_POSICAO >= @Data01
                                        AND CPF.DT_POSICAO <=  @Data02  
                                        AND CPF.IC_AF_POSICAO = 'F' ) ) AND    
		 ( RTRIM( M.CD_TIPO ) = 'TR' ) AND 
		 ( M.CD_PADRAO <> 'V' ) AND		
		 ( MA.DT_LIQUIDACAO_FISICA = MA.DT_TRANSFERENCIA ) AND 
	 	 ( EXISTS ( SELECT CD_FUNDO FROM COTV_ACESSO_FUNDO WHERE DS_LOGIN = 'I500422' AND CD_FUNDO = M.CD_FUNDO ) )

UNION ALL
SELECT M.DT_LIQUIDACAO_FISICA DT_MOVIMENTO,   
		 R.VL_BRUTO_RESGATE VL_BRUTO,   
		 R.QT_COTAS QT_COTAS,   
		 PF.VL_COTA_FECHAMENTO VL_COTA,   
		 M.CD_TIPO CD_TIPO,  
		 R.VL_IOF VL_IOF, 
		 R.VL_IR VL_IR, 
		 M.ID_NOTA ID_NOTA, 
		 M.CD_FUNDO CD_FUNDO, 
		 CF.NM_ABREVIADO NM_FUNDO, 
		 M.CD_COTISTA CD_COTISTA, 
		 CC.NM_CLIENTE NM_COTISTA, 
		 CONVERT( DATETIME, @Data01 ) DT_INICIO, 
		 CONVERT( DATETIME,  @Data02  ) DT_FIM,
		 CONVERT( CHAR( 10 ), M.DT_LIQUIDACAO_FISICA, 103 ) DS_DT_MOVIMENTO,
       M.VL_LIQUIDO VL_LIQUIDO,
       M.DT_LIQUIDACAO_FISICA DT_LIQUIDACAO_FISICA,
       M.DT_LIQUIDACAO_FINANCEIRA DT_LIQUIDACAO_FINANCEIRA, 
       'S' IC_NOME_IMPRESSO,
       M.CD_TIPO_COLAGEM,
       TC.DS_TIPO_COLAGEM,
       CONVERT( CHAR( 459 ), NULL ) DS_MENSAGEM_EXTRATO,
       ISNULL( TT.DS_TIPO_TRANSFERENCIA, '' ) DS_TIPO_TRANSFERENCIA,
       CONVERT( CHAR( 050 ), NULL ) DS_HISTORICO 
  FROM COT_MOVIMENTO M
         INNER JOIN COT_POSICAO_FUNDO PF
           ON M.CD_FUNDO = PF.CD_FUNDO AND
              M.DT_LIQUIDACAO_FISICA = PF.DT_POSICAO 
         LEFT OUTER JOIN COT_TRANSFERENCIA_TIPO TT
            ON M.CD_TIPO_TRANSFERENCIA = TT.CD_TIPO_TRANSFERENCIA
         INNER JOIN COT_FUNDO F
                    INNER JOIN COT_CLIENTE CF
                       ON F.CD_CLIENTE = CF.CD_CLIENTE
           ON M.CD_FUNDO = F.CD_FUNDO
         INNER JOIN COT_COTISTA C
                    INNER JOIN COT_CLIENTE CC 
                       ON C.CD_CLIENTE = CC.CD_CLIENTE
           ON M.CD_COTISTA = C.CD_COTISTA
         INNER JOIN COT_TRANSFERENCIA TR
                    INNER JOIN COT_MOVIMENTO MA
                       ON TR.ID_NOTA_DESTINO = MA.ID_NOTA
           ON M.ID_NOTA = TR.ID_NOTA_RESGATE
         INNER JOIN COT_RESGATE R
           ON M.ID_NOTA = R.ID_NOTA
         LEFT OUTER JOIN COT_MOVIMENTO_TIPO_COLAGEM TC
           ON M.CD_TIPO_COLAGEM = TC.CD_TIPO_COLAGEM
 WHERE ( M.CD_COTISTA IN (  @Cotista  ) ) AND
		 ( M.DT_LIQUIDACAO_FISICA >= @Data01 AND 
         M.DT_LIQUIDACAO_FISICA <= ( SELECT MAX( CPF.DT_POSICAO ) 
                                       FROM COT_POSICAO_FUNDO CPF
                                      WHERE CPF.CD_FUNDO = PF.CD_FUNDO 
                                        AND CPF.DT_POSICAO >= @Data01 
                                        AND CPF.DT_POSICAO <=  @Data02  
                                        AND CPF.IC_AF_POSICAO = 'F' ) ) AND
       ( RTRIM( M.CD_TIPO ) = 'TR' ) AND 
		 ( M.CD_PADRAO <> 'V' ) AND 
		 ( MA.DT_LIQUIDACAO_FISICA <> MA.DT_TRANSFERENCIA ) AND 
	 	 ( EXISTS ( SELECT CD_FUNDO FROM COTV_ACESSO_FUNDO WHERE DS_LOGIN = 'I500422' AND CD_FUNDO = M.CD_FUNDO ) )
UNION ALL
SELECT M.DT_LIQUIDACAO_FISICA DT_MOVIMENTO,   
		 M.VL_BRUTO VL_BRUTO,   
		 M.QT_COTAS QT_COTAS,   
		 ( SELECT ISNULL( MAX( VL_COTA_PRE_EVENTO ), PF.VL_COTA_FECHAMENTO ) 
			  FROM COT_EVENTO E
			 WHERE E.CD_FUNDO = M.CD_FUNDO AND 
					 E.DT_EVENTO = M.DT_LIQUIDACAO_FISICA ) VL_COTA ,   
	 	 M.CD_TIPO CD_TIPO,  
		 M.VL_IOF VL_IOF, 
		 M.VL_IR VL_IR, 
		 M.ID_NOTA ID_NOTA, 
		 M.CD_FUNDO CD_FUNDO, 
		 CF.NM_ABREVIADO NM_FUNDO, 
		 M.CD_COTISTA CD_COTISTA, 
		 CC.NM_CLIENTE NM_COTISTA, 
		 CONVERT( DATETIME, @Data01 ) DT_INICIO, 
		 CONVERT( DATETIME,  @Data02  ) DT_FIM,
		 CONVERT( CHAR( 10 ), M.DT_LIQUIDACAO_FISICA, 103 ) DS_DT_MOVIMENTO,
       M.VL_LIQUIDO VL_LIQUIDO,
       M.DT_LIQUIDACAO_FISICA DT_LIQUIDACAO_FISICA,
       M.DT_LIQUIDACAO_FINANCEIRA DT_LIQUIDACAO_FINANCEIRA,
       'S' IC_NOME_IMPRESSO,
       M.CD_TIPO_COLAGEM,
       TC.DS_TIPO_COLAGEM,
       CONVERT( CHAR( 459 ), NULL ) DS_MENSAGEM_EXTRATO,
       ISNULL( TT.DS_TIPO_TRANSFERENCIA, '' ) DS_TIPO_TRANSFERENCIA,
       CONVERT( CHAR( 050 ), NULL ) DS_HISTORICO 
  FROM COT_MOVIMENTO M
         INNER JOIN COT_POSICAO_FUNDO PF
           ON M.CD_FUNDO = PF.CD_FUNDO AND
              M.DT_LIQUIDACAO_FISICA = PF.DT_POSICAO 
         LEFT OUTER JOIN COT_TRANSFERENCIA_TIPO TT
            ON M.CD_TIPO_TRANSFERENCIA = TT.CD_TIPO_TRANSFERENCIA
         INNER JOIN COT_FUNDO F
                    INNER JOIN COT_CLIENTE CF
                       ON F.CD_CLIENTE = CF.CD_CLIENTE
           ON M.CD_FUNDO = F.CD_FUNDO
         INNER JOIN COT_COTISTA C
                    INNER JOIN COT_CLIENTE CC 
                       ON C.CD_CLIENTE = CC.CD_CLIENTE
           ON M.CD_COTISTA = C.CD_COTISTA
         LEFT OUTER JOIN COT_MOVIMENTO_TIPO_COLAGEM TC
           ON M.CD_TIPO_COLAGEM = TC.CD_TIPO_COLAGEM  
 WHERE ( M.CD_COTISTA IN (  @Cotista  ) ) AND
		 ( M.DT_LIQUIDACAO_FISICA >= @Data01 AND 
         M.DT_LIQUIDACAO_FISICA <= ( SELECT MAX( CPF.DT_POSICAO ) 
                                       FROM COT_POSICAO_FUNDO CPF
                                      WHERE CPF.CD_FUNDO = PF.CD_FUNDO 
                                        AND CPF.DT_POSICAO >= @Data01
                                        AND CPF.DT_POSICAO <=  @Data02  
                                        AND CPF.IC_AF_POSICAO = 'F' ) ) AND
		 ( RTRIM( M.CD_TIPO ) = 'RM' ) AND 
		 ( M.CD_PADRAO <> 'V' ) AND
	 	 ( EXISTS ( SELECT CD_FUNDO FROM COTV_ACESSO_FUNDO WHERE DS_LOGIN = 'I500422' AND CD_FUNDO = M.CD_FUNDO ) )