USE BRD_ACT_YMF_COT
GO

SELECT COT_POSICAO_FUNDO.DT_POSICAO,   
         COT_POSICAO_FUNDO.VL_PATRIMONIO_ABERTURA,   
         COT_POSICAO_FUNDO.VL_COTA_ABERTURA,   
         COT_POSICAO_FUNDO.VL_PATRIMONIO_FECHAMENTO_TOTAL,   
         COT_POSICAO_FUNDO.CD_FUNDO,   
         COT_CLIENTE.NM_CLIENTE,   
         COT_CLIENTE.NM_ABREVIADO,   
         COT_POSICAO_FUNDO.VL_COTA_FECHAMENTO,   
         COT_POSICAO_FUNDO.QT_COTAS_TOTAL,   
         COT_POSICAO_FUNDO.QT_COTAS_FECHAMENTO_TOTAL,   
         COT_POSICAO_FUNDO.VL_COTA_PRE_PFEE,   
         COT_POSICAO_FUNDO.VL_PFEE_ACUMULADO,   
         COT_POSICAO_FUNDO.VL_PFEE_RESGATADO,   
         COT_POSICAO_FUNDO.VL_RECEITA_PFEE  
    FROM COT_POSICAO_FUNDO,   
         COT_CLIENTE,   
         COT_FUNDO  
   WHERE ( COT_FUNDO.CD_CLIENTE = COT_CLIENTE.CD_CLIENTE ) and  
         ( COT_FUNDO.CD_FUNDO = COT_POSICAO_FUNDO.CD_FUNDO ) and  
         ( COT_POSICAO_FUNDO.CD_FUNDO IN (:cd_fundo) ) AND  
         ( COT_POSICAO_FUNDO.DT_POSICAO >= :dt_posicao_ini ) AND  
         ( COT_POSICAO_FUNDO.DT_POSICAO <= :dt_posicao_fim )    