USE BRD_ACT_YMF_COT
GO

SELECT COT_POSICAO_NOTA.DT_POSICAO,
       COT_POSICAO_NOTA.CD_COTISTA,
       COT_CLIENTE_C.NM_CLIENTE NM_COTISTA,
       COT_POSICAO_NOTA.CD_FUNDO,
       COT_CLIENTE_F.NM_ABREVIADO NM_FUNDO,
       COT_POSICAO_FUNDO.IC_AF_POSICAO,
       COT_POSICAO_FUNDO.VL_COTA_ABERTURA,
       COT_POSICAO_FUNDO.VL_COTA_FECHAMENTO,
       ( SELECT ISNULL( SUM( ISNULL( COT_BLOQUEIO.QT_COTAS, 0) ), 0)
           FROM COT_BLOQUEIO
          WHERE ( COT_BLOQUEIO.CD_COTISTA = COT_POSICAO_NOTA.CD_COTISTA ) AND  
                ( COT_BLOQUEIO.CD_FUNDO = COT_POSICAO_NOTA.CD_FUNDO ) AND  
                ( ( ( COT_BLOQUEIO.IC_SN_BLOQUEADA = 'S' ) AND  
                    ( COT_BLOQUEIO.CD_TIPO_BLOQUEIO IN ('M','B') ) AND
                    ( COT_BLOQUEIO.DT_BLOQUEIO <= :dt_posicao ) ) OR
                  ( ( COT_BLOQUEIO.CD_TIPO_BLOQUEIO = 'A' ) AND  
                    ( COT_BLOQUEIO.DT_BLOQUEIO <= :dt_posicao AND
                      COT_BLOQUEIO.DT_DESBLOQUEIO > :dt_posicao ) ) )AND
                ( COT_BLOQUEIO.CD_BLOQUEIO = 'C') ) QT_COTAS_BLOQUEIO,
       ( SELECT ISNULL( SUM( ISNULL( COT_BLOQUEIO.VL_BLOQUEIO, 0) ), 0)
           FROM COT_BLOQUEIO
          WHERE ( COT_BLOQUEIO.CD_COTISTA = COT_POSICAO_NOTA.CD_COTISTA ) AND  
                ( COT_BLOQUEIO.CD_FUNDO = COT_POSICAO_NOTA.CD_FUNDO ) AND  
                ( ( ( COT_BLOQUEIO.IC_SN_BLOQUEADA = 'S' ) AND  
                    ( COT_BLOQUEIO.CD_TIPO_BLOQUEIO IN ('M','B') ) AND
                    ( COT_BLOQUEIO.DT_BLOQUEIO <= :dt_posicao ) ) OR
                  ( ( COT_BLOQUEIO.CD_TIPO_BLOQUEIO = 'A' ) AND  
                    ( COT_BLOQUEIO.DT_BLOQUEIO <= :dt_posicao AND
                      COT_BLOQUEIO.DT_DESBLOQUEIO > :dt_posicao ) ) )AND
                ( COT_BLOQUEIO.CD_BLOQUEIO = 'B') ) VL_BRUTO_BLOQUEIO,
       ( SELECT ISNULL( SUM( ISNULL( COT_BLOQUEIO.VL_BLOQUEIO, 0) ), 0)
           FROM COT_BLOQUEIO
          WHERE ( COT_BLOQUEIO.CD_COTISTA = COT_POSICAO_NOTA.CD_COTISTA ) AND  
                ( COT_BLOQUEIO.CD_FUNDO = COT_POSICAO_NOTA.CD_FUNDO ) AND  
                ( ( ( COT_BLOQUEIO.IC_SN_BLOQUEADA = 'S' ) AND  
                    ( COT_BLOQUEIO.CD_TIPO_BLOQUEIO IN ('M','B') ) AND
                    ( COT_BLOQUEIO.DT_BLOQUEIO <= :dt_posicao ) ) OR
                  ( ( COT_BLOQUEIO.CD_TIPO_BLOQUEIO = 'A' ) AND  
                    ( COT_BLOQUEIO.DT_BLOQUEIO <= :dt_posicao AND
                      COT_BLOQUEIO.DT_DESBLOQUEIO > :dt_posicao ) ) )AND
                ( COT_BLOQUEIO.CD_BLOQUEIO = 'L') ) VL_LIQUIDO_BLOQUEIO,
       SUM( COT_POSICAO_NOTA.QT_COTAS ) + ISNULL( SUM( COT_RESGATE_PROVISORIO.QT_COTAS ),0 ) QT_COTAS,
       SUM( COT_POSICAO_NOTA.VL_APLICACAO ) + ISNULL( SUM( COT_RESGATE_PROVISORIO.VL_APLICACAO ),0 ) VL_APLICACAO,
       SUM( COT_POSICAO_NOTA.VL_CORRIGIDO ) + ISNULL( SUM( COT_RESGATE_PROVISORIO.VL_CORRIGIDO ),0 )VL_CORRIGIDO,
       SUM( COT_POSICAO_NOTA.VL_IR ) + ISNULL( SUM( COT_RESGATE_PROVISORIO.VL_IR ),0 ) VL_IR,
       SUM( COT_POSICAO_NOTA.VL_IOF ) + ISNULL( SUM( COT_RESGATE_PROVISORIO.VL_IOF ),0 )VL_IOF,
       SUM( COT_POSICAO_NOTA.VL_RESGATE ) + ISNULL( SUM( COT_RESGATE_PROVISORIO.VL_LIQUIDO_RESGATE ),0 ) VL_RESGATE
  FROM COT_POSICAO_NOTA LEFT OUTER JOIN COT_RESGATE_PROVISORIO
          ON ( COT_RESGATE_PROVISORIO.ID_NOTA_APLICACAO = COT_POSICAO_NOTA.ID_NOTA ) AND
             ( COT_RESGATE_PROVISORIO.DT_POSICAO = COT_POSICAO_NOTA.DT_POSICAO ),
       COT_CLIENTE COT_CLIENTE_C,
       COT_CLIENTE COT_CLIENTE_F,
       COT_POSICAO_FUNDO,
       COT_FUNDO,
       COT_COTISTA,
       COT_MOVIMENTO
 WHERE ( COT_POSICAO_NOTA.CD_FUNDO = COT_FUNDO.CD_FUNDO ) AND
       ( COT_FUNDO.CD_CLIENTE = COT_CLIENTE_F.CD_CLIENTE ) AND
       ( COT_POSICAO_NOTA.CD_COTISTA = COT_COTISTA.CD_COTISTA ) AND
       ( COT_COTISTA.CD_CLIENTE = COT_CLIENTE_C.CD_CLIENTE ) AND
       ( COT_POSICAO_NOTA.CD_FUNDO = COT_POSICAO_FUNDO.CD_FUNDO ) AND
       ( COT_POSICAO_NOTA.DT_POSICAO = COT_POSICAO_FUNDO.DT_POSICAO ) AND
       ( COT_POSICAO_NOTA.ID_NOTA = COT_MOVIMENTO.ID_NOTA ) AND
       ( COT_MOVIMENTO.DT_LIQUIDACAO_FISICA <= COT_POSICAO_NOTA.DT_POSICAO ) AND
       ( COT_POSICAO_NOTA.CD_FUNDO IN ( :cd_fundo ) ) AND
       ( COT_POSICAO_NOTA.DT_POSICAO = :dt_posicao ) AND
       ( COT_POSICAO_FUNDO.IC_AF_POSICAO = 'A' ) AND
       ( EXISTS ( SELECT COTV_ACESSO_FUNDO.CD_FUNDO FROM COTV_ACESSO_FUNDO 
                   WHERE COTV_ACESSO_FUNDO.DS_LOGIN = :ds_login and COTV_ACESSO_FUNDO.CD_FUNDO = COT_FUNDO.CD_FUNDO ) )
GROUP BY COT_POSICAO_NOTA.DT_POSICAO,
         COT_POSICAO_NOTA.CD_COTISTA,
         COT_CLIENTE_C.NM_CLIENTE,
         COT_POSICAO_NOTA.CD_FUNDO,
         COT_CLIENTE_F.NM_ABREVIADO,
         COT_POSICAO_FUNDO.IC_AF_POSICAO,
         COT_POSICAO_FUNDO.VL_COTA_ABERTURA,
         COT_POSICAO_FUNDO.VL_COTA_FECHAMENTO

UNION

SELECT COT_POSICAO_NOTA_HISTORICO.DT_POSICAO,
       COT_POSICAO_NOTA_HISTORICO.CD_COTISTA,
       COT_CLIENTE_C.NM_CLIENTE NM_COTISTA,
       COT_POSICAO_NOTA_HISTORICO.CD_FUNDO,
       COT_CLIENTE_F.NM_ABREVIADO NM_FUNDO,
       COT_POSICAO_FUNDO.IC_AF_POSICAO,
       COT_POSICAO_FUNDO.VL_COTA_ABERTURA,
       COT_POSICAO_FUNDO.VL_COTA_FECHAMENTO,
       ( SELECT ISNULL( SUM( ISNULL( COT_BLOQUEIO.QT_COTAS, 0) ), 0)
           FROM COT_BLOQUEIO
          WHERE ( COT_BLOQUEIO.CD_COTISTA = COT_POSICAO_NOTA_HISTORICO.CD_COTISTA ) AND  
                ( COT_BLOQUEIO.CD_FUNDO = COT_POSICAO_NOTA_HISTORICO.CD_FUNDO ) AND  
                ( ( ( COT_BLOQUEIO.IC_SN_BLOQUEADA = 'S' ) AND  
                    ( COT_BLOQUEIO.CD_TIPO_BLOQUEIO IN ('M','B') ) AND
                    ( COT_BLOQUEIO.DT_BLOQUEIO <= :dt_posicao ) ) OR
                  ( ( COT_BLOQUEIO.CD_TIPO_BLOQUEIO = 'A' ) AND  
                    ( COT_BLOQUEIO.DT_BLOQUEIO <= :dt_posicao AND
                      COT_BLOQUEIO.DT_DESBLOQUEIO > :dt_posicao ) ) )AND
                ( COT_BLOQUEIO.CD_BLOQUEIO = 'C') ) QT_COTAS_BLOQUEIO,
       ( SELECT ISNULL( SUM( ISNULL( COT_BLOQUEIO.VL_BLOQUEIO, 0) ), 0)
           FROM COT_BLOQUEIO
          WHERE ( COT_BLOQUEIO.CD_COTISTA = COT_POSICAO_NOTA_HISTORICO.CD_COTISTA ) AND  
                ( COT_BLOQUEIO.CD_FUNDO = COT_POSICAO_NOTA_HISTORICO.CD_FUNDO ) AND  
                ( ( ( COT_BLOQUEIO.IC_SN_BLOQUEADA = 'S' ) AND  
                    ( COT_BLOQUEIO.CD_TIPO_BLOQUEIO IN ('M','B') ) AND
                    ( COT_BLOQUEIO.DT_BLOQUEIO <= :dt_posicao ) ) OR
                  ( ( COT_BLOQUEIO.CD_TIPO_BLOQUEIO = 'A' ) AND  
                    ( COT_BLOQUEIO.DT_BLOQUEIO <= :dt_posicao AND
                      COT_BLOQUEIO.DT_DESBLOQUEIO > :dt_posicao ) ) )AND
                ( COT_BLOQUEIO.CD_BLOQUEIO = 'B') ) VL_BRUTO_BLOQUEIO,
       ( SELECT ISNULL( SUM( ISNULL( COT_BLOQUEIO.VL_BLOQUEIO, 0) ), 0)
           FROM COT_BLOQUEIO
          WHERE ( COT_BLOQUEIO.CD_COTISTA = COT_POSICAO_NOTA_HISTORICO.CD_COTISTA ) AND  
                ( COT_BLOQUEIO.CD_FUNDO = COT_POSICAO_NOTA_HISTORICO.CD_FUNDO ) AND  
                ( ( ( COT_BLOQUEIO.IC_SN_BLOQUEADA = 'S' ) AND  
                    ( COT_BLOQUEIO.CD_TIPO_BLOQUEIO IN ('M','B') ) AND
                    ( COT_BLOQUEIO.DT_BLOQUEIO <= :dt_posicao ) ) OR
                  ( ( COT_BLOQUEIO.CD_TIPO_BLOQUEIO = 'A' ) AND  
                    ( COT_BLOQUEIO.DT_BLOQUEIO <= :dt_posicao AND
                      COT_BLOQUEIO.DT_DESBLOQUEIO > :dt_posicao ) ) )AND
                ( COT_BLOQUEIO.CD_BLOQUEIO = 'L') ) VL_LIQUIDO_BLOQUEIO,
       SUM( COT_POSICAO_NOTA_HISTORICO.QT_COTAS ) + ISNULL( SUM( COT_RESGATE_PROVISORIO.QT_COTAS ),0 ) QT_COTAS,
       SUM( COT_POSICAO_NOTA_HISTORICO.VL_APLICACAO ) + ISNULL( SUM( COT_RESGATE_PROVISORIO.VL_APLICACAO ),0 ) VL_APLICACAO,
       SUM( COT_POSICAO_NOTA_HISTORICO.VL_CORRIGIDO ) + ISNULL( SUM( COT_RESGATE_PROVISORIO.VL_CORRIGIDO ),0 )VL_CORRIGIDO,
       SUM( COT_POSICAO_NOTA_HISTORICO.VL_IR ) + ISNULL( SUM( COT_RESGATE_PROVISORIO.VL_IR ),0 ) VL_IR,
       SUM( COT_POSICAO_NOTA_HISTORICO.VL_IOF ) + ISNULL( SUM( COT_RESGATE_PROVISORIO.VL_IOF ),0 )VL_IOF,
       SUM( COT_POSICAO_NOTA_HISTORICO.VL_RESGATE ) + ISNULL( SUM( COT_RESGATE_PROVISORIO.VL_LIQUIDO_RESGATE ),0 ) VL_RESGATE
  FROM COT_POSICAO_NOTA_HISTORICO LEFT OUTER JOIN COT_RESGATE_PROVISORIO
          ON ( COT_RESGATE_PROVISORIO.ID_NOTA_APLICACAO = COT_POSICAO_NOTA_HISTORICO.ID_NOTA ) AND
             ( COT_RESGATE_PROVISORIO.DT_POSICAO = COT_POSICAO_NOTA_HISTORICO.DT_POSICAO ),
       COT_CLIENTE COT_CLIENTE_C,
       COT_CLIENTE COT_CLIENTE_F,
       COT_POSICAO_FUNDO,
       COT_FUNDO,
       COT_COTISTA,
       COT_MOVIMENTO
 WHERE ( COT_POSICAO_NOTA_HISTORICO.CD_FUNDO = COT_FUNDO.CD_FUNDO ) AND
       ( COT_FUNDO.CD_CLIENTE = COT_CLIENTE_F.CD_CLIENTE ) AND
       ( COT_POSICAO_NOTA_HISTORICO.CD_COTISTA = COT_COTISTA.CD_COTISTA ) AND
       ( COT_COTISTA.CD_CLIENTE = COT_CLIENTE_C.CD_CLIENTE ) AND
       ( COT_POSICAO_NOTA_HISTORICO.CD_FUNDO = COT_POSICAO_FUNDO.CD_FUNDO ) AND
       ( COT_POSICAO_NOTA_HISTORICO.DT_POSICAO = COT_POSICAO_FUNDO.DT_POSICAO ) AND
       ( COT_POSICAO_NOTA_HISTORICO.ID_NOTA = COT_MOVIMENTO.ID_NOTA ) AND
       ( COT_MOVIMENTO.DT_LIQUIDACAO_FISICA <= COT_POSICAO_NOTA_HISTORICO.DT_POSICAO ) AND
       ( COT_POSICAO_NOTA_HISTORICO.CD_FUNDO IN ( :cd_fundo ) ) AND
       ( COT_POSICAO_NOTA_HISTORICO.DT_POSICAO = :dt_posicao ) AND
       ( COT_POSICAO_FUNDO.IC_AF_POSICAO = 'F' ) AND
       ( EXISTS ( SELECT COTV_ACESSO_FUNDO.CD_FUNDO FROM COTV_ACESSO_FUNDO 
                   WHERE COTV_ACESSO_FUNDO.DS_LOGIN = :ds_login and COTV_ACESSO_FUNDO.CD_FUNDO = COT_FUNDO.CD_FUNDO ) )
GROUP BY COT_POSICAO_NOTA_HISTORICO.DT_POSICAO,
         COT_POSICAO_NOTA_HISTORICO.CD_COTISTA,
         COT_CLIENTE_C.NM_CLIENTE,
         COT_POSICAO_NOTA_HISTORICO.CD_FUNDO,
         COT_CLIENTE_F.NM_ABREVIADO,
         COT_POSICAO_FUNDO.IC_AF_POSICAO,
         COT_POSICAO_FUNDO.VL_COTA_ABERTURA,
         COT_POSICAO_FUNDO.VL_COTA_FECHAMENTO