USE BRD_ACT_YMF_COT
GO

SELECT DISTINCT
       COT_MOVIMENTO.ID_NOTA,
       COT_MOVIMENTO.CD_COTISTA,
       COT_MOVIMENTO.CD_PADRAO,
       COT_MOVIMENTO.CD_FUNDO,
       RTRIM( COT_MOVIMENTO.CD_TIPO ) CD_TIPO,
       COT_MOVIMENTO.DT_MOVIMENTO,
       COT_MOVIMENTO.DT_LIQUIDACAO_FISICA,
       COT_MOVIMENTO.DT_LIQUIDACAO_FINANCEIRA,
       CONVERT( CHAR, COT_MOVIMENTO.DT_MOVIMENTO, 103 ) DS_DT_MOVIMENTO,
       CONVERT( CHAR, COT_MOVIMENTO.DT_LIQUIDACAO_FISICA, 103 ) DS_DT_LIQUIDACAO_FISICA,
       CONVERT( CHAR, COT_MOVIMENTO.DT_LIQUIDACAO_FINANCEIRA, 103 ) DS_DT_LIQUIDACAO_FINANCEIRA,
       COT_MOVIMENTO.VL_BRUTO,
       COT_MOVIMENTO.VL_IR,
       COT_MOVIMENTO.QT_COTAS,
       COT_MOVIMENTO.VL_IOF,
       COT_MOVIMENTO.VL_LIQUIDO,
       COT_RESGATE.ID_NOTA_APLICACAO,
       CASE RTRIM( COT_MOVIMENTO.CD_TIPO)
        WHEN 'TR' THEN 'Resgate por Transferência'
        ELSE COT_MOVIMENTO_TIPO.DS_TIPO
       END DS_TIPO,
       COT_RESGATE.QT_COTAS,
       COT_RESGATE.VL_APLICACAO,
       COT_RESGATE.VL_RECEITA_SAQUE_CARENCIA,
       COT_RESGATE.VL_IOF,
       COT_RESGATE.VL_BRUTO_RESGATE,
       COT_RESGATE.VL_IR,
       COT_RESGATE.VL_PENALTY_FEE,
       COT_RESGATE.VL_LIQUIDO_RESGATE,
       COT_MOVIMENTO.CD_LIQUIDACAO,
       COT_MOVIMENTO.CD_CLEARING,
       COT_MOVIMENTO_CLEARING.DS_CLEARING,
       COT_MOVIMENTO.IC_AR_LIQUIDACAO,
       COT_CLIENTE_b.NM_ABREVIADO,
       COT_CLIENTE_a.NM_CLIENTE,
       COT_RESGATE.VL_CORRIGIDO,
       COT_COTISTA.DS_TITULARIDADE,
       COT_FUNDO.CD_GESTOR,
       COT_MOVIMENTO_TIPO.IC_AR_MOVIMENTO,
       COT_MOVIMENTO.DT_TRANSFERENCIA,
       COT_COTISTA.CD_INTERFACE_4,
       COT_MOVIMENTO_LIQUIDACAO.DS_LIQUIDACAO,
       ISNULL( COT_MOVIMENTO.CD_TIPO_TRANSFERENCIA, '01' ) CD_TIPO_TRANSFERENCIA,
       ISNULL( COT_TRANSFERENCIA_TIPO.DS_TIPO_TRANSFERENCIA, '') DS_TIPO_TRANSFERENCIA,
       ISNULL( COT_MOVIMENTO.ID_BANCO, COT_CONTA_EXTERNA.ID_BANCO  ) ID_BANCO,
       ISNULL( COT_MOVIMENTO.CD_AGENCIA_EXTERNA, COT_CONTA_EXTERNA.CD_AGENCIA_EXTERNA  ) CD_AGENCIA_EXTERNA,
       ISNULL( COT_MOVIMENTO.CD_CONTA_EXTERNA, COT_CONTA_EXTERNA.CD_CONTA_EXTERNA  ) CD_CONTA_EXTERNA,
       COT_CLIENTE_a.IC_FJ_PESSOA IC_FJ_PESSOA,
       COT_CLIENTE_a.NO_CPF NO_CPF,
       COT_CLIENTE_a.NO_CGC NO_CGC,
       COT_MOVIMENTO.IC_SN_MOV_RESTAURADO,
       COT_MOVIMENTO.CD_CONTA_EXTERNA CD_CONTA_EXTERNA_MOV,
       COT_CONTA_EXTERNA.DV_CONTA_EXTERNA,
       CONVERT( CHAR, NULL ) DS_CONTA_LIQUIDACAO,
       CONVERT( CHAR, NULL ) CO_TITULAR,
       COT_MOVIMENTO.IC_SN_DISTR_RENDIMENTO
  FROM COT_CLIENTE COT_CLIENTE_a
       INNER JOIN COT_COTISTA
        INNER JOIN COT_MOVIMENTO
          INNER JOIN COT_FUNDO
              INNER JOIN COT_CLIENTE COT_CLIENTE_b
                 ON COT_FUNDO.CD_CLIENTE = COT_CLIENTE_b.CD_CLIENTE
                 ON COT_MOVIMENTO.CD_FUNDO = COT_FUNDO.CD_FUNDO
         INNER JOIN COT_MOVIMENTO_TIPO
              ON COT_MOVIMENTO.CD_TIPO = COT_MOVIMENTO_TIPO.CD_TIPO
         INNER JOIN COT_MOVIMENTO_LIQUIDACAO
              ON COT_MOVIMENTO.CD_LIQUIDACAO = COT_MOVIMENTO_LIQUIDACAO.CD_LIQUIDACAO
         LEFT OUTER JOIN COT_RESGATE
              ON COT_MOVIMENTO.ID_NOTA = COT_RESGATE.ID_NOTA
         LEFT OUTER JOIN COT_MOVIMENTO_CLEARING
              ON COT_MOVIMENTO.CD_CLEARING = COT_MOVIMENTO_CLEARING.CD_CLEARING
         LEFT OUTER JOIN COT_TRANSFERENCIA_TIPO
              ON COT_MOVIMENTO.CD_TIPO_TRANSFERENCIA = COT_TRANSFERENCIA_TIPO.CD_TIPO_TRANSFERENCIA
              ON COT_COTISTA.CD_COTISTA = COT_MOVIMENTO.CD_COTISTA
       INNER JOIN COTV_ACESSO_OPERADOR
          ON COT_COTISTA.CD_DISTRIBUIDOR = COTV_ACESSO_OPERADOR.CD_DISTRIBUIDOR AND
             COT_COTISTA.CD_OPERADOR = ISNULL( COTV_ACESSO_OPERADOR.CD_OPERADOR, COT_COTISTA.CD_OPERADOR ) AND
             COT_COTISTA.CD_EMPRESA = COTV_ACESSO_OPERADOR.CD_EMPRESA
          ON COT_CLIENTE_a.CD_CLIENTE = COT_COTISTA.CD_CLIENTE
       LEFT OUTER JOIN COT_CONTA_EXTERNA
            ON COT_COTISTA.CD_COTISTA = COT_CONTA_EXTERNA.CD_COTISTA AND
               ( ( COT_MOVIMENTO.ID_BANCO  = COT_CONTA_EXTERNA.ID_BANCO AND
                   COT_MOVIMENTO.CD_AGENCIA_EXTERNA = COT_CONTA_EXTERNA.CD_AGENCIA_EXTERNA AND
                   COT_MOVIMENTO.CD_CONTA_EXTERNA   = COT_CONTA_EXTERNA.CD_CONTA_EXTERNA AND
                   COT_MOVIMENTO.CD_COTISTA   = COT_CONTA_EXTERNA.CD_COTISTA ) OR
                  ( COT_CONTA_EXTERNA.IC_SN_DEFAULT = 'S' AND
                    COT_MOVIMENTO.CD_CONTA_EXTERNA IS NULL ) ) AND
               CASE CASE RTRIM( COT_MOVIMENTO.CD_TIPO )
                     WHEN 'RM' THEN ISNULL( COT_COTISTA.CD_LIQUIDACAO_DEFAULT, 'LI')
                     ELSE COT_MOVIMENTO.CD_LIQUIDACAO
                    END
                WHEN 'TV' THEN 'I'
                WHEN 'DV' THEN 'I'
                WHEN 'IV' THEN 'I'
                WHEN 'CE' THEN 'S'
                WHEN 'TC' THEN 'N'
                WHEN 'CC' THEN 'N'
                WHEN 'D'  THEN 'N'
                WHEN 'TC' THEN 'N'
                WHEN 'TE' THEN 'N'
                WHEN 'TK' THEN 'N'
               END = COT_CONTA_EXTERNA.CD_TIPO_CONTA
 WHERE ( COT_MOVIMENTO.CD_FUNDO IN ( :cd_fundo ) ) AND
       ( COT_MOVIMENTO.DT_MOVIMENTO BETWEEN :dt_inicio AND :dt_fim ) AND
       ( COT_MOVIMENTO.CD_PADRAO <> 'V' ) AND
       ( COT_MOVIMENTO.CD_PADRAO <> 'A' ) AND
       ( COT_MOVIMENTO.DT_TRANSFERENCIA IS NULL ) AND
       ( COT_MOVIMENTO.CD_TIPO_COLAGEM IS NULL ) AND
       ( COTV_ACESSO_OPERADOR.DS_LOGIN = :ds_login )

UNION

SELECT DISTINCT
       COT_MOVIMENTO.ID_NOTA,
       COT_MOVIMENTO.CD_COTISTA,
       COT_MOVIMENTO.CD_PADRAO,
       COT_MOVIMENTO.CD_FUNDO,
       RTRIM( COT_MOVIMENTO.CD_TIPO ) CD_TIPO,
       COT_MOVIMENTO.DT_MOVIMENTO,
       COT_MOVIMENTO.DT_LIQUIDACAO_FISICA,
       COT_MOVIMENTO.DT_LIQUIDACAO_FINANCEIRA,
       CONVERT( CHAR, COT_MOVIMENTO.DT_MOVIMENTO, 103 ) DS_DT_MOVIMENTO,
       CONVERT( CHAR, COT_MOVIMENTO.DT_LIQUIDACAO_FISICA, 103 ) DS_DT_LIQUIDACAO_FISICA,
       CONVERT( CHAR, COT_MOVIMENTO.DT_LIQUIDACAO_FINANCEIRA, 103 ) DS_DT_LIQUIDACAO_FINANCEIRA,
       COT_MOVIMENTO.VL_BRUTO,
       COT_MOVIMENTO.VL_IR,
       COT_MOVIMENTO.QT_COTAS,
       COT_MOVIMENTO.VL_IOF,
       COT_MOVIMENTO.VL_LIQUIDO,
       COT_RESGATE.ID_NOTA_APLICACAO,
       CASE RTRIM( COT_MOVIMENTO.CD_TIPO)
        WHEN 'TR' THEN 'Resgate por Transferência'
        WHEN 'A'  THEN 'Aplicação por Transferência'
        ELSE COT_MOVIMENTO_TIPO.DS_TIPO
       END DS_TIPO,
       COT_RESGATE.QT_COTAS,
       COT_RESGATE.VL_APLICACAO,
       COT_RESGATE.VL_RECEITA_SAQUE_CARENCIA,
       COT_RESGATE.VL_IOF,
       COT_RESGATE.VL_BRUTO_RESGATE,
       COT_RESGATE.VL_IR,
       COT_RESGATE.VL_PENALTY_FEE,
       COT_RESGATE.VL_LIQUIDO_RESGATE,
       COT_MOVIMENTO.CD_LIQUIDACAO,
       COT_MOVIMENTO.CD_CLEARING,
       COT_MOVIMENTO_CLEARING.DS_CLEARING,
       COT_MOVIMENTO.IC_AR_LIQUIDACAO,
       COT_CLIENTE_b.NM_ABREVIADO,
       COT_CLIENTE_a.NM_CLIENTE,
       COT_RESGATE.VL_CORRIGIDO,
       COT_COTISTA.DS_TITULARIDADE,
       COT_FUNDO.CD_GESTOR,
       COT_MOVIMENTO_TIPO.IC_AR_MOVIMENTO,
       COT_MOVIMENTO.DT_TRANSFERENCIA,
       COT_COTISTA.CD_INTERFACE_4,
       COT_MOVIMENTO_LIQUIDACAO.DS_LIQUIDACAO,
       ISNULL( COT_MOVIMENTO.CD_TIPO_TRANSFERENCIA, '01' ) CD_TIPO_TRANSFERENCIA,
       ISNULL( COT_TRANSFERENCIA_TIPO.DS_TIPO_TRANSFERENCIA, '') DS_TIPO_TRANSFERENCIA,
       ISNULL( COT_MOVIMENTO.ID_BANCO, COT_CONTA_EXTERNA.ID_BANCO  ) ID_BANCO,
       ISNULL( COT_MOVIMENTO.CD_AGENCIA_EXTERNA, COT_CONTA_EXTERNA.CD_AGENCIA_EXTERNA  ) CD_AGENCIA_EXTERNA,
       ISNULL( COT_MOVIMENTO.CD_CONTA_EXTERNA, COT_CONTA_EXTERNA.CD_CONTA_EXTERNA  ) CD_CONTA_EXTERNA,
       COT_CLIENTE_a.IC_FJ_PESSOA IC_FJ_PESSOA,
       COT_CLIENTE_a.NO_CPF NO_CPF,
       COT_CLIENTE_a.NO_CGC NO_CGC,
       COT_MOVIMENTO.IC_SN_MOV_RESTAURADO,
       COT_MOVIMENTO.CD_CONTA_EXTERNA CD_CONTA_EXTERNA_MOV,
       COT_CONTA_EXTERNA.DV_CONTA_EXTERNA,
       CONVERT( CHAR, NULL ) DS_CONTA_LIQUIDACAO,
       CONVERT( CHAR, NULL ) CO_TITULAR,
       COT_MOVIMENTO.IC_SN_DISTR_RENDIMENTO
  FROM COT_CLIENTE COT_CLIENTE_a
       INNER JOIN COT_COTISTA
        INNER JOIN COT_MOVIMENTO
           INNER JOIN COT_FUNDO
              INNER JOIN COT_CLIENTE COT_CLIENTE_b
                 ON COT_FUNDO.CD_CLIENTE = COT_CLIENTE_b.CD_CLIENTE
                 ON COT_MOVIMENTO.CD_FUNDO = COT_FUNDO.CD_FUNDO
         INNER JOIN COT_MOVIMENTO_TIPO
              ON COT_MOVIMENTO.CD_TIPO = COT_MOVIMENTO_TIPO.CD_TIPO
         INNER JOIN COT_MOVIMENTO_LIQUIDACAO
              ON COT_MOVIMENTO.CD_LIQUIDACAO = COT_MOVIMENTO_LIQUIDACAO.CD_LIQUIDACAO
         LEFT OUTER JOIN COT_RESGATE
              ON COT_MOVIMENTO.ID_NOTA = COT_RESGATE.ID_NOTA
         LEFT OUTER JOIN COT_MOVIMENTO_CLEARING
              ON COT_MOVIMENTO.CD_CLEARING = COT_MOVIMENTO_CLEARING.CD_CLEARING
         LEFT OUTER JOIN COT_TRANSFERENCIA_TIPO
              ON COT_MOVIMENTO.CD_TIPO_TRANSFERENCIA = COT_TRANSFERENCIA_TIPO.CD_TIPO_TRANSFERENCIA
              ON COT_COTISTA.CD_COTISTA = COT_MOVIMENTO.CD_COTISTA
       INNER JOIN COTV_ACESSO_OPERADOR
           ON COT_COTISTA.CD_DISTRIBUIDOR = COTV_ACESSO_OPERADOR.CD_DISTRIBUIDOR AND
              COT_COTISTA.CD_OPERADOR = ISNULL( COTV_ACESSO_OPERADOR.CD_OPERADOR, COT_COTISTA.CD_OPERADOR )AND
              COT_COTISTA.CD_EMPRESA = COTV_ACESSO_OPERADOR.CD_EMPRESA
           ON COT_CLIENTE_a.CD_CLIENTE = COT_COTISTA.CD_CLIENTE
       LEFT OUTER JOIN COT_CONTA_EXTERNA
           ON COT_COTISTA.CD_COTISTA = COT_CONTA_EXTERNA.CD_COTISTA AND
              ( ( COT_MOVIMENTO.ID_BANCO  = COT_CONTA_EXTERNA.ID_BANCO AND
                  COT_MOVIMENTO.CD_AGENCIA_EXTERNA = COT_CONTA_EXTERNA.CD_AGENCIA_EXTERNA AND
                  COT_MOVIMENTO.CD_CONTA_EXTERNA   = COT_CONTA_EXTERNA.CD_CONTA_EXTERNA AND
                  COT_MOVIMENTO.CD_COTISTA   = COT_CONTA_EXTERNA.CD_COTISTA ) OR
                 ( COT_CONTA_EXTERNA.IC_SN_DEFAULT = 'S' AND
                   COT_MOVIMENTO.CD_CONTA_EXTERNA IS NULL ) ) AND
              CASE CASE RTRIM( COT_MOVIMENTO.CD_TIPO )
                    WHEN 'RM' THEN ISNULL( COT_COTISTA.CD_LIQUIDACAO_DEFAULT, 'LI')
                    ELSE COT_MOVIMENTO.CD_LIQUIDACAO
                   END
               WHEN 'TV' THEN 'I'
               WHEN 'DV' THEN 'I'
               WHEN 'IV' THEN 'I'
               WHEN 'CE' THEN 'S'
               WHEN 'TC' THEN 'N'
               WHEN 'CC' THEN 'N'
               WHEN 'D'  THEN 'N'
               WHEN 'TC' THEN 'N'
               WHEN 'TE' THEN 'N'
               WHEN 'TK' THEN 'N'
             END = COT_CONTA_EXTERNA.CD_TIPO_CONTA
 WHERE ( COT_MOVIMENTO.CD_FUNDO IN ( :cd_fundo ) ) AND
       ( COT_MOVIMENTO.DT_TRANSFERENCIA BETWEEN :dt_inicio AND :dt_fim ) AND
       ( COT_MOVIMENTO.CD_PADRAO <> 'V' ) AND
       ( COT_MOVIMENTO.CD_PADRAO <> 'A' ) AND
       ( COT_MOVIMENTO.DT_TRANSFERENCIA IS NOT NULL ) AND
       ( COT_MOVIMENTO.CD_TIPO_COLAGEM IS NULL ) AND
       ( COTV_ACESSO_OPERADOR.DS_LOGIN = :ds_login )

UNION

SELECT DISTINCT
       COT_MOVIMENTO.ID_NOTA,
       COT_MOVIMENTO.CD_COTISTA,
       COT_MOVIMENTO.CD_PADRAO,
       COT_MOVIMENTO.CD_FUNDO,
       RTRIM( COT_MOVIMENTO.CD_TIPO ) CD_TIPO,
       COT_MOVIMENTO.DT_MOVIMENTO,
       COT_MOVIMENTO.DT_LIQUIDACAO_FISICA,
       COT_MOVIMENTO.DT_LIQUIDACAO_FINANCEIRA,
       CONVERT( CHAR, COT_MOVIMENTO.DT_MOVIMENTO, 103 ) DS_DT_MOVIMENTO,
       CONVERT( CHAR, COT_MOVIMENTO.DT_LIQUIDACAO_FISICA, 103 ) DS_DT_LIQUIDACAO_FISICA,
       CONVERT( CHAR, COT_MOVIMENTO.DT_LIQUIDACAO_FINANCEIRA, 103 ) DS_DT_LIQUIDACAO_FINANCEIRA,
       COT_MOVIMENTO.VL_BRUTO,
       COT_MOVIMENTO.VL_IR,
       COT_MOVIMENTO.QT_COTAS,
       COT_MOVIMENTO.VL_IOF,
       COT_MOVIMENTO.VL_LIQUIDO,
       COT_RESGATE.ID_NOTA_APLICACAO,
       COT_MOVIMENTO_TIPO_COLAGEM.DS_TIPO_COLAGEM DS_TIPO,
       COT_RESGATE.QT_COTAS,
       COT_RESGATE.VL_APLICACAO,
       COT_RESGATE.VL_RECEITA_SAQUE_CARENCIA,
       COT_RESGATE.VL_IOF,
       COT_RESGATE.VL_BRUTO_RESGATE,
       COT_RESGATE.VL_IR,
       COT_RESGATE.VL_PENALTY_FEE,
       COT_RESGATE.VL_LIQUIDO_RESGATE,
       COT_MOVIMENTO.CD_LIQUIDACAO,
       COT_MOVIMENTO.CD_CLEARING,
       COT_MOVIMENTO_CLEARING.DS_CLEARING,
       COT_MOVIMENTO.IC_AR_LIQUIDACAO,
       COT_CLIENTE_b.NM_ABREVIADO,
       COT_CLIENTE_a.NM_CLIENTE,
       COT_RESGATE.VL_CORRIGIDO,
       COT_COTISTA.DS_TITULARIDADE,
       COT_FUNDO.CD_GESTOR,
       COT_MOVIMENTO_TIPO.IC_AR_MOVIMENTO,
       COT_MOVIMENTO.DT_TRANSFERENCIA,
       COT_COTISTA.CD_INTERFACE_4,
       COT_MOVIMENTO_LIQUIDACAO.DS_LIQUIDACAO,
       ISNULL( COT_MOVIMENTO.CD_TIPO_TRANSFERENCIA, '01' ) CD_TIPO_TRANSFERENCIA,
       ISNULL( COT_TRANSFERENCIA_TIPO.DS_TIPO_TRANSFERENCIA, '') DS_TIPO_TRANSFERENCIA,
       ISNULL( COT_MOVIMENTO.ID_BANCO, COT_CONTA_EXTERNA.ID_BANCO  ) ID_BANCO,
       ISNULL( COT_MOVIMENTO.CD_AGENCIA_EXTERNA, COT_CONTA_EXTERNA.CD_AGENCIA_EXTERNA  ) CD_AGENCIA_EXTERNA,
       ISNULL( COT_MOVIMENTO.CD_CONTA_EXTERNA, COT_CONTA_EXTERNA.CD_CONTA_EXTERNA  ) CD_CONTA_EXTERNA,
       COT_CLIENTE_a.IC_FJ_PESSOA IC_FJ_PESSOA,
       COT_CLIENTE_a.NO_CPF NO_CPF,
       COT_CLIENTE_a.NO_CGC NO_CGC,
       COT_MOVIMENTO.IC_SN_MOV_RESTAURADO,
       COT_MOVIMENTO.CD_CONTA_EXTERNA CD_CONTA_EXTERNA_MOV,
       COT_CONTA_EXTERNA.DV_CONTA_EXTERNA,
       CONVERT( CHAR, NULL ) DS_CONTA_LIQUIDACAO,
       CONVERT( CHAR, NULL ) CO_TITULAR,
       COT_MOVIMENTO.IC_SN_DISTR_RENDIMENTO
  FROM COT_CLIENTE COT_CLIENTE_a
       INNER JOIN COT_COTISTA
        INNER JOIN COT_MOVIMENTO
           INNER JOIN COT_FUNDO
              INNER JOIN COT_CLIENTE COT_CLIENTE_b
                 ON COT_FUNDO.CD_CLIENTE = COT_CLIENTE_b.CD_CLIENTE
                 ON COT_MOVIMENTO.CD_FUNDO = COT_FUNDO.CD_FUNDO
         INNER JOIN COT_MOVIMENTO_TIPO
              ON COT_MOVIMENTO.CD_TIPO = COT_MOVIMENTO_TIPO.CD_TIPO
         INNER JOIN COT_MOVIMENTO_LIQUIDACAO
              ON COT_MOVIMENTO.CD_LIQUIDACAO = COT_MOVIMENTO_LIQUIDACAO.CD_LIQUIDACAO
         INNER JOIN COT_MOVIMENTO_TIPO_COLAGEM
              ON COT_MOVIMENTO.CD_TIPO_COLAGEM = COT_MOVIMENTO_TIPO_COLAGEM.CD_TIPO_COLAGEM
         LEFT OUTER JOIN COT_RESGATE
              ON COT_MOVIMENTO.ID_NOTA = COT_RESGATE.ID_NOTA
         LEFT OUTER JOIN COT_MOVIMENTO_CLEARING
              ON COT_MOVIMENTO.CD_CLEARING = COT_MOVIMENTO_CLEARING.CD_CLEARING
         LEFT OUTER JOIN COT_TRANSFERENCIA_TIPO
              ON COT_MOVIMENTO.CD_TIPO_TRANSFERENCIA = COT_TRANSFERENCIA_TIPO.CD_TIPO_TRANSFERENCIA
              ON COT_COTISTA.CD_COTISTA = COT_MOVIMENTO.CD_COTISTA
       INNER JOIN COTV_ACESSO_OPERADOR
           ON COT_COTISTA.CD_DISTRIBUIDOR = COTV_ACESSO_OPERADOR.CD_DISTRIBUIDOR AND
              COT_COTISTA.CD_OPERADOR = ISNULL( COTV_ACESSO_OPERADOR.CD_OPERADOR, COT_COTISTA.CD_OPERADOR ) AND
              COT_COTISTA.CD_EMPRESA = COTV_ACESSO_OPERADOR.CD_EMPRESA
           ON COT_CLIENTE_a.CD_CLIENTE = COT_COTISTA.CD_CLIENTE
       LEFT OUTER JOIN COT_CONTA_EXTERNA
           ON COT_COTISTA.CD_COTISTA = COT_CONTA_EXTERNA.CD_COTISTA AND
              ( ( COT_MOVIMENTO.ID_BANCO  = COT_CONTA_EXTERNA.ID_BANCO AND
                  COT_MOVIMENTO.CD_AGENCIA_EXTERNA = COT_CONTA_EXTERNA.CD_AGENCIA_EXTERNA AND
                  COT_MOVIMENTO.CD_CONTA_EXTERNA = COT_CONTA_EXTERNA.CD_CONTA_EXTERNA AND
                  COT_MOVIMENTO.CD_COTISTA = COT_CONTA_EXTERNA.CD_COTISTA ) OR
                 ( COT_CONTA_EXTERNA.IC_SN_DEFAULT = 'S' AND
                   COT_MOVIMENTO.CD_CONTA_EXTERNA IS NULL ) ) AND
               CASE CASE RTRIM( COT_MOVIMENTO.CD_TIPO )
                     WHEN 'RM' THEN ISNULL( COT_COTISTA.CD_LIQUIDACAO_DEFAULT, 'LI')
                     ELSE COT_MOVIMENTO.CD_LIQUIDACAO
                    END
                WHEN 'TV' THEN 'I'
                WHEN 'DV' THEN 'I'
                WHEN 'IV' THEN 'I'
                WHEN 'CE' THEN 'S'
                WHEN 'TC' THEN 'N'
                WHEN 'CC' THEN 'N'
                WHEN 'D'  THEN 'N'
                WHEN 'TC' THEN 'N'
                WHEN 'TE' THEN 'N'
                WHEN 'TK' THEN 'N'
               END = COT_CONTA_EXTERNA.CD_TIPO_CONTA
 WHERE ( COT_MOVIMENTO.CD_FUNDO IN ( :cd_fundo ) ) AND
       ( COT_MOVIMENTO.DT_MOVIMENTO BETWEEN :dt_inicio AND :dt_fim ) AND
       ( COT_MOVIMENTO.CD_PADRAO <> 'V' ) AND
       ( COT_MOVIMENTO.CD_PADRAO <> 'A' ) AND
       ( COT_MOVIMENTO.DT_TRANSFERENCIA IS NULL ) AND
       ( COTV_ACESSO_OPERADOR.DS_LOGIN = :ds_login )