USE BRD_ACT_YMF_COT
GO

SELECT DISTINCT 
       COT_MOVIMENTO.ID_NOTA , 
       COT_MOVIMENTO.CD_COTISTA , 
       COT_MOVIMENTO.CD_PADRAO , 
       COT_MOVIMENTO.CD_FUNDO , 
       COT_MOVIMENTO.CD_TIPO , 
       COT_MOVIMENTO.DT_MOVIMENTO , 
       COT_MOVIMENTO.DT_LIQUIDACAO_FISICA , 
       COT_MOVIMENTO.DT_LIQUIDACAO_FINANCEIRA , 
       COT_MOVIMENTO.VL_BRUTO , 
       COT_MOVIMENTO.QT_COTAS, 
       COT_MOVIMENTO.VL_LIQUIDO , 
       COT_RESGATE.ID_NOTA_APLICACAO , 
       COT_MOVIMENTO_TIPO.DS_TIPO , 
       COT_RESGATE.QT_COTAS QT_COTAS_RESGATE, 
       COT_RESGATE.VL_APLICACAO VL_APLICACAO_RESGATE, 
       COT_RESGATE.VL_BRUTO_RESGATE VL_BRUTO_RESGATE, 
       COT_RESGATE.VL_LIQUIDO_RESGATE VL_LIQUIDO_RESGATE, 
       COT_MOVIMENTO.CD_LIQUIDACAO ,
       COT_MOVIMENTO.IC_AR_LIQUIDACAO, 
       COT_CLIENTE_b.NM_ABREVIADO , 
       COT_CLIENTE_a.NM_CLIENTE , 
       COT_RESGATE.VL_CORRIGIDO ,    
       COT_COTISTA.DS_TITULARIDADE , 
       COT_FUNDO.CD_GESTOR,
       COT_MOVIMENTO_TIPO.IC_AR_MOVIMENTO,
       COT_RESGATE.VL_COTA_UTILIZADA VL_COTA_UTILIZADA,
       CONVERT( CHAR, COT_MOVIMENTO_APLIC.DT_MOVIMENTO, 103 ) DT_MOVIMENTO_APLIC,
       CONVERT( CHAR, COT_MOVIMENTO_APLIC.DT_LIQUIDACAO_FISICA, 103 ) DT_LIQUIDACAO_FISICA_APLIC,
       CONVERT( CHAR, COT_MOVIMENTO_APLIC.DT_LIQUIDACAO_FINANCEIRA, 103 ) DT_LIQUIDACAO_FINANCEIRA_APLIC,
       COT_MOVIMENTO_APLIC.CD_LIQUIDACAO CD_LIQUIDACAO_APLIC,
       COT_RESGATE.VL_COTA_APLICACAO VL_COTA_UTILIZADA_APLIC,
       COT_MOVIMENTO.IC_SN_MOV_RESTAURADO,
		 ISNULL( COT_MOVIMENTO.ID_BANCO, CE.ID_BANCO  ) ID_BANCO,
       ISNULL( COT_MOVIMENTO.CD_AGENCIA_EXTERNA, CE.CD_AGENCIA_EXTERNA  ) CD_AGENCIA_EXTERNA,
       ISNULL( COT_MOVIMENTO.CD_CONTA_EXTERNA, CE.CD_CONTA_EXTERNA  ) CD_CONTA_EXTERNA,
       RTRIM( CE.DV_CONTA_EXTERNA ) DV_CONTA_EXTERNA, 		 
       ELG.NM_LOGOTIPO NM_LOGOTIPO_EMP,
       ALG.NM_LOGOTIPO NM_LOGOTIPO_ADM,
       COT_FUNDO.CD_EMPRESA,
       CADM.NM_CLIENTE NM_ADMINISTRADOR,
       COT_FUNDO.CD_ADMINISTRADOR,
       CEMP.NM_CLIENTE NM_EMPRESA
  FROM COT_COTISTA 
          INNER JOIN COT_MOVIMENTO 
             ON COT_COTISTA.CD_COTISTA = COT_MOVIMENTO.CD_COTISTA 
          LEFT OUTER JOIN COT_CONTA_EXTERNA CE
             LEFT OUTER JOIN COT_AGENCIA_EXTERNA AE
               ON AE.CD_AGENCIA_EXTERNA = CE.CD_AGENCIA_EXTERNA
              AND AE.ID_BANCO           = CE.ID_BANCO
             ON COT_COTISTA.CD_COTISTA = CE.CD_COTISTA
            AND ( ( COT_MOVIMENTO.ID_BANCO           = CE.ID_BANCO AND 
                    COT_MOVIMENTO.CD_AGENCIA_EXTERNA = CE.CD_AGENCIA_EXTERNA AND 
                    COT_MOVIMENTO.CD_CONTA_EXTERNA   = CE.CD_CONTA_EXTERNA AND
                    COT_MOVIMENTO.CD_COTISTA         = CE.CD_COTISTA ) OR 
                  ( CE.IC_SN_DEFAULT = 'S' AND
                    COT_MOVIMENTO.CD_CONTA_EXTERNA IS NULL ) ) 
            AND CASE CASE RTRIM( COT_MOVIMENTO.CD_TIPO ) WHEN 'RM' THEN ISNULL( COT_COTISTA.CD_LIQUIDACAO_DEFAULT, 'LI') 
                     ELSE COT_MOVIMENTO.CD_LIQUIDACAO END 
                     WHEN 'TV' THEN 'I' 
                     WHEN 'DV' THEN 'I' 
                     WHEN 'IV' THEN 'I' 
                     WHEN 'CE' THEN 'S' 
                     WHEN 'TC' THEN 'N' 
                     WHEN 'CC' THEN 'N'
                     WHEN 'D'  THEN 'N'
                     WHEN 'TC' THEN 'N'
                     WHEN 'TE' THEN 'N'
                     WHEN 'TK' THEN 'N' END = CE.CD_TIPO_CONTA,
       COT_MOVIMENTO COT_MOVIMENTO_APLIC ,
       COT_RESGATE , 
       COT_CLIENTE COT_CLIENTE_a , 
       COT_FUNDO
         LEFT JOIN NET_ADM_EMPRESA_LOGO ELG 
                ON ELG.CD_EMPRESA = COT_FUNDO.CD_EMPRESA
         LEFT JOIN NET_ADM_ADMINISTRADOR_LOGO ALG
                ON ALG.CD_ADMINISTRADOR = COT_FUNDO.CD_ADMINISTRADOR 
			INNER JOIN COT_ADMINISTRADOR ADM
            LEFT JOIN COT_CLIENTE CADM
              ON CADM.CD_CLIENTE = ADM.CD_CLIENTE
            ON ADM.CD_ADMINISTRADOR = COT_FUNDO.CD_ADMINISTRADOR
         LEFT JOIN COT_EMPRESA EMP
            INNER JOIN COT_CLIENTE CEMP
               ON CEMP.CD_CLIENTE = EMP.CD_CLIENTE
            ON EMP.CD_EMPRESA = COT_FUNDO.CD_EMPRESA,
       COT_CLIENTE COT_CLIENTE_b , 
       COT_MOVIMENTO_TIPO 
 WHERE ( COT_RESGATE.ID_NOTA = COT_MOVIMENTO.ID_NOTA ) AND 
       ( COT_COTISTA.CD_CLIENTE = COT_CLIENTE_a.CD_CLIENTE ) AND 
       ( COT_FUNDO.CD_FUNDO = COT_MOVIMENTO.CD_FUNDO ) AND 
       ( COT_FUNDO.CD_CLIENTE = COT_CLIENTE_b.CD_CLIENTE ) AND 
       ( COT_MOVIMENTO_TIPO.CD_TIPO = COT_MOVIMENTO.CD_TIPO ) AND
       ( COT_RESGATE.ID_NOTA_APLICACAO = COT_MOVIMENTO_APLIC.ID_NOTA ) AND
       ( COT_MOVIMENTO.CD_FUNDO IN (  @Fundo  ) ) AND
       ( COT_MOVIMENTO.DT_MOVIMENTO BETWEEN  @Data01  AND  @Data02  ) AND
       ( COT_MOVIMENTO.CD_PADRAO <> 'V' ) AND
       ( COT_MOVIMENTO.CD_PADRAO <> 'A' ) AND
		 ( EXISTS ( SELECT COT_COTISTA.CD_DISTRIBUIDOR FROM COTV_ACESSO_OPERADOR WHERE DS_LOGIN = 'I500422' AND
                         COT_COTISTA.CD_OPERADOR     = ISNULL( COTV_ACESSO_OPERADOR.CD_OPERADOR, COT_COTISTA.CD_OPERADOR ) AND 
								 COT_COTISTA.CD_DISTRIBUIDOR = COTV_ACESSO_OPERADOR.CD_DISTRIBUIDOR AND 
								 COT_COTISTA.CD_EMPRESA      = COTV_ACESSO_OPERADOR.CD_EMPRESA ) ) 

UNION

SELECT DISTINCT COT_MOVIMENTO.ID_NOTA , 
       COT_MOVIMENTO.CD_COTISTA , 
       COT_MOVIMENTO.CD_PADRAO , 
       COT_MOVIMENTO.CD_FUNDO , 
       COT_MOVIMENTO.CD_TIPO , 
       COT_MOVIMENTO.DT_MOVIMENTO , 
       COT_MOVIMENTO.DT_LIQUIDACAO_FISICA , 
       COT_MOVIMENTO.DT_LIQUIDACAO_FINANCEIRA , 
       COT_MOVIMENTO.VL_BRUTO , 
       COT_MOVIMENTO.QT_COTAS QT_COTAS , 
       COT_MOVIMENTO.VL_LIQUIDO VL_LIQUIDO , 
       0 ID_NOTA_APLICACAO , 
       COT_MOVIMENTO_TIPO.DS_TIPO , 
       0 QT_COTAS_RESGATE , 
       0 VL_APLICACAO_RESGATE , 
       0 VL_BRUTO_RESGATE , 
       0 VL_LIQUIDO_RESGATE , 
       COT_MOVIMENTO.CD_LIQUIDACAO ,
	    COT_MOVIMENTO.IC_AR_LIQUIDACAO, 
       COT_CLIENTE_b.NM_ABREVIADO , 
       COT_CLIENTE_a.NM_CLIENTE , 
       0 VL_CORRIGIDO ,    
       COT_COTISTA.DS_TITULARIDADE , 
       COT_FUNDO.CD_GESTOR,
	    COT_MOVIMENTO_TIPO.IC_AR_MOVIMENTO,
       COT_POSICAO_FUNDO.VL_COTA_FECHAMENTO VL_COTA_UTILIZADA,
       CONVERT( CHAR, COT_MOVIMENTO.DT_MOVIMENTO, 103 ) DT_MOVIMENTO_APLIC,
       CONVERT( CHAR, COT_MOVIMENTO.DT_LIQUIDACAO_FISICA, 103 ) DT_LIQUIDACAO_FISICA_APLIC,
       CONVERT( CHAR, COT_MOVIMENTO.DT_LIQUIDACAO_FINANCEIRA, 103 ) DT_LIQUIDACAO_FINANCEIRA_APLIC,
       CONVERT( CHAR, COT_MOVIMENTO.CD_LIQUIDACAO ) CD_LIQUIDACAO_APLIC,
       COT_POSICAO_FUNDO.VL_COTA_FECHAMENTO VL_COTA_UTILIZADA_APLIC,
       COT_MOVIMENTO.IC_SN_MOV_RESTAURADO,
		 ISNULL( COT_MOVIMENTO.ID_BANCO, CE.ID_BANCO  ) ID_BANCO,
       ISNULL( COT_MOVIMENTO.CD_AGENCIA_EXTERNA, CE.CD_AGENCIA_EXTERNA  ) CD_AGENCIA_EXTERNA,
       ISNULL( COT_MOVIMENTO.CD_CONTA_EXTERNA, CE.CD_CONTA_EXTERNA  ) CD_CONTA_EXTERNA,
       RTRIM( CE.DV_CONTA_EXTERNA ) DV_CONTA_EXTERNA, 		 
       ELG.NM_LOGOTIPO NM_LOGOTIPO_EMP,
       ALG.NM_LOGOTIPO NM_LOGOTIPO_ADM,
       COT_FUNDO.CD_EMPRESA,
       CADM.NM_CLIENTE NM_ADMINISTRADOR,
       COT_FUNDO.CD_ADMINISTRADOR,
       CEMP.NM_CLIENTE NM_EMPRESA
  FROM COT_COTISTA 
          INNER JOIN COT_MOVIMENTO 
             ON COT_COTISTA.CD_COTISTA = COT_MOVIMENTO.CD_COTISTA 
          LEFT OUTER JOIN COT_CONTA_EXTERNA CE
             LEFT OUTER JOIN COT_AGENCIA_EXTERNA AE
               ON AE.CD_AGENCIA_EXTERNA = CE.CD_AGENCIA_EXTERNA
              AND AE.ID_BANCO           = CE.ID_BANCO
             ON COT_COTISTA.CD_COTISTA = CE.CD_COTISTA
            AND ( ( COT_MOVIMENTO.ID_BANCO           = CE.ID_BANCO AND 
                    COT_MOVIMENTO.CD_AGENCIA_EXTERNA = CE.CD_AGENCIA_EXTERNA AND 
                    COT_MOVIMENTO.CD_CONTA_EXTERNA   = CE.CD_CONTA_EXTERNA AND
                    COT_MOVIMENTO.CD_COTISTA         = CE.CD_COTISTA ) OR 
                  ( CE.IC_SN_DEFAULT = 'S' AND
                    COT_MOVIMENTO.CD_CONTA_EXTERNA IS NULL ) ) 
            AND CASE CASE RTRIM( COT_MOVIMENTO.CD_TIPO ) WHEN 'RM' THEN ISNULL( COT_COTISTA.CD_LIQUIDACAO_DEFAULT, 'LI') 
                     ELSE COT_MOVIMENTO.CD_LIQUIDACAO END 
                     WHEN 'TV' THEN 'I' 
                     WHEN 'DV' THEN 'I' 
                     WHEN 'IV' THEN 'I' 
                     WHEN 'CE' THEN 'S' 
                     WHEN 'TC' THEN 'N' 
                     WHEN 'CC' THEN 'N'
                     WHEN 'D'  THEN 'N'
                     WHEN 'TC' THEN 'N'
                     WHEN 'TE' THEN 'N'
                     WHEN 'TK' THEN 'N' END = CE.CD_TIPO_CONTA,
       COT_POSICAO_FUNDO ,
       COT_CLIENTE COT_CLIENTE_a , 
       COT_FUNDO
         LEFT JOIN NET_ADM_EMPRESA_LOGO ELG 
                ON ELG.CD_EMPRESA = COT_FUNDO.CD_EMPRESA
         LEFT JOIN NET_ADM_ADMINISTRADOR_LOGO ALG
                ON ALG.CD_ADMINISTRADOR = COT_FUNDO.CD_ADMINISTRADOR
			INNER JOIN COT_ADMINISTRADOR ADM
            LEFT JOIN COT_CLIENTE CADM
              ON CADM.CD_CLIENTE = ADM.CD_CLIENTE
            ON ADM.CD_ADMINISTRADOR = COT_FUNDO.CD_ADMINISTRADOR
         LEFT JOIN COT_EMPRESA EMP
            INNER JOIN COT_CLIENTE CEMP
               ON CEMP.CD_CLIENTE = EMP.CD_CLIENTE
            ON EMP.CD_EMPRESA = COT_FUNDO.CD_EMPRESA,
       COT_CLIENTE COT_CLIENTE_b , 
       COT_MOVIMENTO_TIPO 
 WHERE ( COT_COTISTA.CD_CLIENTE = COT_CLIENTE_a.CD_CLIENTE ) AND 
             ( COT_FUNDO.CD_FUNDO = COT_MOVIMENTO.CD_FUNDO ) AND 
       ( COT_FUNDO.CD_CLIENTE = COT_CLIENTE_b.CD_CLIENTE ) AND 
       ( COT_MOVIMENTO_TIPO.CD_TIPO = COT_MOVIMENTO.CD_TIPO ) AND
       ( COT_POSICAO_FUNDO.CD_FUNDO = COT_MOVIMENTO.CD_FUNDO ) AND
       ( COT_POSICAO_FUNDO.DT_POSICAO = COT_MOVIMENTO.DT_LIQUIDACAO_FISICA ) AND
       ( COT_MOVIMENTO.CD_FUNDO IN (  @Fundo  ) ) AND
       ( COT_MOVIMENTO.DT_MOVIMENTO BETWEEN  @Data01  AND  @Data02  ) AND
       ( COT_MOVIMENTO.CD_PADRAO <> 'V' ) AND
       ( COT_MOVIMENTO.CD_PADRAO <> 'A' ) AND
       ( COT_MOVIMENTO.CD_TIPO IN ( 'A', 'AC', 'AG' ) ) AND
		 ( EXISTS ( SELECT COT_COTISTA.CD_DISTRIBUIDOR FROM COTV_ACESSO_OPERADOR WHERE DS_LOGIN = 'I500422' AND 
                         COT_COTISTA.CD_OPERADOR     = ISNULL( COTV_ACESSO_OPERADOR.CD_OPERADOR, COT_COTISTA.CD_OPERADOR ) AND
								 COT_COTISTA.CD_DISTRIBUIDOR = COTV_ACESSO_OPERADOR.CD_DISTRIBUIDOR AND 
								 COT_COTISTA.CD_EMPRESA      = COTV_ACESSO_OPERADOR.CD_EMPRESA ) )