USE BRD_ACT_YMF_COT
GO

DECLARE 
@Data01 date = '2016-10-25 00:00:00.000' 
,@Fundo char(15) = '007530'  

SELECT  COT_POSICAO_NOTA_HISTORICO.ID_NOTA,   
          COT_POSICAO_NOTA_HISTORICO.CD_FUNDO , 
          COT_POSICAO_NOTA_HISTORICO.DT_POSICAO , 
          COT_POSICAO_NOTA_HISTORICO.QT_COTAS , 
          COT_POSICAO_NOTA_HISTORICO.VL_CORRIGIDO , 
          COT_CLIENTE_a.IC_FJ_PESSOA , 
          COT_POSICAO_NOTA_HISTORICO.CD_COTISTA , 
          COT_CLIENTE_b.NM_ABREVIADO , 
          COT_CLIENTE_a.NM_CLIENTE , 
          COT_POSICAO_NOTA_HISTORICO.VL_CORRIGIDO , 
          COT_POSICAO_FUNDO.VL_COTA_FECHAMENTO ,
			 COT_CLIENTE_b.NO_CGC,
          COT_EMPRESA.CD_EMPRESA,
          CEMP.NM_CLIENTE NM_EMPRESA,
          COT_FUNDO.CD_ADMINISTRADOR,
          CADM.NM_CLIENTE NM_ADMINISTRADOR,
          NET_ADM_EMPRESA_LOGO.NM_LOGOTIPO NM_LOGO_EMPRESA,
          NET_ADM_ADMINISTRADOR_LOGO.NM_LOGOTIPO NM_LOGO_ADMINISTRADOR,
			 ( SELECT SUM( QT_COTAS ) 
              FROM COT_POSICAO_NOTA_HISTORICO HIS
             INNER JOIN COT_COTISTA COT
                ON HIS.CD_COTISTA = COT.CD_COTISTA
             WHERE CD_FUNDO   = COT_FUNDO.CD_FUNDO
               AND DT_POSICAO = @Data01 
               AND ( EXISTS ( SELECT COT.CD_DISTRIBUIDOR FROM COTV_ACESSO_OPERADOR WHERE DS_LOGIN = 'I500422' 
                                 AND COT.CD_OPERADOR = ISNULL( COTV_ACESSO_OPERADOR.CD_OPERADOR, COT.CD_OPERADOR )
 								         AND COT.CD_DISTRIBUIDOR = COTV_ACESSO_OPERADOR.CD_DISTRIBUIDOR 
                                 AND COT.CD_EMPRESA = COTV_ACESSO_OPERADOR.CD_EMPRESA ) ) ) + 
			 ( SELECT ISNULL( SUM( QT_COTAS ), 0 ) 
              FROM COT_RESGATE_PROVISORIO PROV
             WHERE PROV.ID_NOTA IN ( SELECT ID_NOTA 
                                     FROM COT_MOVIMENTO MOV
                                    INNER JOIN COT_COTISTA COT
                                       ON MOV.CD_COTISTA = COT.CD_COTISTA
                                    WHERE MOV.CD_FUNDO             = COT_FUNDO.CD_FUNDO
                                      AND MOV.DT_LIQUIDACAO_FISICA >= @Data01  
                                      AND COT.CD_EMPRESA = COT_EMPRESA.CD_EMPRESA  
                                      AND ( EXISTS ( SELECT COT.CD_DISTRIBUIDOR FROM COTV_ACESSO_OPERADOR WHERE DS_LOGIN = 'I500422' 
                                                        AND COT.CD_OPERADOR = ISNULL( COTV_ACESSO_OPERADOR.CD_OPERADOR, COT.CD_OPERADOR )
                                                        AND COT.CD_DISTRIBUIDOR = COTV_ACESSO_OPERADOR.CD_DISTRIBUIDOR 
                                                        AND COT.CD_EMPRESA = COTV_ACESSO_OPERADOR.CD_EMPRESA ) ) ) 
               AND DT_POSICAO = @Data01  )   QT_COTAS_TOTAL_FUNDO,
			0.00 PC_PARTICIP
     FROM COT_CLIENTE COT_CLIENTE_a , 
          COT_COTISTA , 
          COT_POSICAO_NOTA_HISTORICO  
             INNER JOIN COT_MOVIMENTO
                ON COT_POSICAO_NOTA_HISTORICO.ID_NOTA = COT_MOVIMENTO.ID_NOTA,
          COT_CLIENTE COT_CLIENTE_b , 
          COT_FUNDO 
				 INNER JOIN COT_EMPRESA
					 LEFT JOIN NET_ADM_EMPRESA_LOGO
						 ON NET_ADM_EMPRESA_LOGO.CD_EMPRESA = COT_EMPRESA.CD_EMPRESA
					 INNER JOIN COT_CLIENTE CEMP
						 ON CEMP.CD_CLIENTE = COT_EMPRESA.CD_CLIENTE
					 ON COT_FUNDO.CD_EMPRESA = COT_EMPRESA.CD_EMPRESA
				 LEFT JOIN NET_ADM_ADMINISTRADOR_LOGO
					 ON NET_ADM_ADMINISTRADOR_LOGO.CD_ADMINISTRADOR = COT_FUNDO.CD_ADMINISTRADOR
				 INNER JOIN COT_ADMINISTRADOR 
					INNER JOIN COT_CLIENTE CADM
						ON CADM.CD_CLIENTE = COT_ADMINISTRADOR.CD_CLIENTE
					 ON COT_ADMINISTRADOR.CD_ADMINISTRADOR = COT_FUNDO.CD_ADMINISTRADOR,
          COT_POSICAO_FUNDO 
    WHERE ( COT_POSICAO_FUNDO.CD_FUNDO IN (  @Fundo  ) ) and 
          ( COT_POSICAO_FUNDO.DT_POSICAO = @Data01  ) and 
          ( COT_POSICAO_NOTA_HISTORICO.CD_FUNDO = COT_POSICAO_FUNDO.CD_FUNDO ) and 
          ( COT_POSICAO_NOTA_HISTORICO.DT_POSICAO = COT_POSICAO_FUNDO.DT_POSICAO ) and 
          ( COT_COTISTA.CD_CLIENTE = COT_CLIENTE_a.CD_CLIENTE ) and 
          ( COT_POSICAO_NOTA_HISTORICO.CD_COTISTA = COT_COTISTA.CD_COTISTA ) and 
          ( COT_CLIENTE_b.CD_CLIENTE = COT_FUNDO.CD_CLIENTE ) and 
          ( COT_POSICAO_NOTA_HISTORICO.CD_FUNDO = COT_FUNDO.CD_FUNDO ) and 
          ( COT_POSICAO_FUNDO.CD_FUNDO = COT_FUNDO.CD_FUNDO ) and 
          ( COT_POSICAO_FUNDO.CD_FUNDO = COT_POSICAO_NOTA_HISTORICO.CD_FUNDO ) and 
          ( COT_POSICAO_FUNDO.DT_POSICAO = COT_POSICAO_NOTA_HISTORICO.DT_POSICAO ) and 
          ( COT_MOVIMENTO.DT_LIQUIDACAO_FISICA <= @Data01  ) and
		    ( EXISTS ( SELECT COT_COTISTA.CD_DISTRIBUIDOR FROM COTV_ACESSO_OPERADOR 
                      WHERE DS_LOGIN = 'I500422' 
                        AND COT_COTISTA.CD_OPERADOR = ISNULL( COTV_ACESSO_OPERADOR.CD_OPERADOR, COT_COTISTA.CD_OPERADOR )
                        AND COT_COTISTA.CD_DISTRIBUIDOR = COTV_ACESSO_OPERADOR.CD_DISTRIBUIDOR 
                        AND COT_COTISTA.CD_EMPRESA = COTV_ACESSO_OPERADOR.CD_EMPRESA ) ) 

UNION ALL

  SELECT  COT_RESGATE_PROVISORIO.ID_NOTA,   
          COT_POSICAO_NOTA_HISTORICO.CD_FUNDO , 
          COT_POSICAO_NOTA_HISTORICO.DT_POSICAO , 
          COT_RESGATE_PROVISORIO.QT_COTAS , 
          COT_RESGATE_PROVISORIO.VL_CORRIGIDO , 
          COT_CLIENTE_a.IC_FJ_PESSOA , 
          COT_POSICAO_NOTA_HISTORICO.CD_COTISTA , 
          COT_CLIENTE_b.NM_ABREVIADO , 
          COT_CLIENTE_a.NM_CLIENTE , 
          COT_RESGATE_PROVISORIO.VL_CORRIGIDO , 
          COT_POSICAO_FUNDO.VL_COTA_FECHAMENTO ,
			 COT_CLIENTE_b.NO_CGC,
          COT_EMPRESA.CD_EMPRESA,
          CEMP.NM_CLIENTE NM_EMPRESA,
          COT_FUNDO.CD_ADMINISTRADOR,
          CADM.NM_CLIENTE NM_ADMINISTRADOR,
          NET_ADM_EMPRESA_LOGO.NM_LOGOTIPO NM_LOGO_EMPRESA,
          NET_ADM_ADMINISTRADOR_LOGO.NM_LOGOTIPO NM_LOGO_ADMINISTRADOR,
			 0.00 QT_COTAS_TOTAL_FUNDO,
			 0.00 PC_PARTICIP
     FROM COT_CLIENTE COT_CLIENTE_a , 
          COT_COTISTA , 
          COT_POSICAO_NOTA_HISTORICO ,
          COT_RESGATE_PROVISORIO,
          COT_CLIENTE COT_CLIENTE_b , 
          COT_FUNDO
          INNER JOIN COT_EMPRESA
             LEFT JOIN NET_ADM_EMPRESA_LOGO
                ON NET_ADM_EMPRESA_LOGO.CD_EMPRESA = COT_EMPRESA.CD_EMPRESA
             INNER JOIN COT_CLIENTE CEMP
                ON CEMP.CD_CLIENTE = COT_EMPRESA.CD_CLIENTE
             ON COT_FUNDO.CD_EMPRESA = COT_EMPRESA.CD_EMPRESA
          LEFT JOIN NET_ADM_ADMINISTRADOR_LOGO
             ON NET_ADM_ADMINISTRADOR_LOGO.CD_ADMINISTRADOR = COT_FUNDO.CD_ADMINISTRADOR
          INNER JOIN COT_ADMINISTRADOR 
            INNER JOIN COT_CLIENTE CADM
               ON CADM.CD_CLIENTE = COT_ADMINISTRADOR.CD_CLIENTE
             ON COT_ADMINISTRADOR.CD_ADMINISTRADOR = COT_FUNDO.CD_ADMINISTRADOR,
          COT_POSICAO_FUNDO 
    WHERE ( COT_POSICAO_FUNDO.CD_FUNDO IN (  @Fundo  ) ) and 
          ( COT_POSICAO_FUNDO.DT_POSICAO = @Data01  ) and 
          ( COT_POSICAO_NOTA_HISTORICO.CD_FUNDO = COT_POSICAO_FUNDO.CD_FUNDO ) and 
          ( COT_POSICAO_NOTA_HISTORICO.DT_POSICAO = COT_POSICAO_FUNDO.DT_POSICAO ) and 
          ( COT_COTISTA.CD_CLIENTE = COT_CLIENTE_a.CD_CLIENTE ) and 
          ( COT_RESGATE_PROVISORIO.ID_NOTA_APLICACAO  = COT_POSICAO_NOTA_HISTORICO.ID_NOTA ) and 
          ( COT_POSICAO_NOTA_HISTORICO.CD_COTISTA = COT_COTISTA.CD_COTISTA ) and 
          ( COT_CLIENTE_b.CD_CLIENTE = COT_FUNDO.CD_CLIENTE ) and 
          ( COT_POSICAO_NOTA_HISTORICO.CD_FUNDO = COT_FUNDO.CD_FUNDO ) and 
          ( COT_POSICAO_FUNDO.CD_FUNDO = COT_FUNDO.CD_FUNDO ) and 
          ( COT_POSICAO_FUNDO.CD_FUNDO = COT_POSICAO_NOTA_HISTORICO.CD_FUNDO ) and 
          ( COT_POSICAO_FUNDO.DT_POSICAO = COT_POSICAO_NOTA_HISTORICO.DT_POSICAO ) and 
          ( COT_RESGATE_PROVISORIO.DT_POSICAO = COT_POSICAO_NOTA_HISTORICO.DT_POSICAO ) and 
		    ( EXISTS ( SELECT COT_COTISTA.CD_DISTRIBUIDOR FROM COTV_ACESSO_OPERADOR 
                      WHERE DS_LOGIN = 'I500422' 
                        AND COT_COTISTA.CD_OPERADOR = ISNULL( COTV_ACESSO_OPERADOR.CD_OPERADOR, COT_COTISTA.CD_OPERADOR )
                        AND COT_COTISTA.CD_DISTRIBUIDOR = COTV_ACESSO_OPERADOR.CD_DISTRIBUIDOR 
                        AND COT_COTISTA.CD_EMPRESA = COTV_ACESSO_OPERADOR.CD_EMPRESA ) )