USE BRD_ACT_YMF_COT
GO

DECLARE 
@Data01 date =  '2016-10-25 00:00:00.000'   
,@Fundo char(15) =  '007530'    


SELECT COT_CLIENTE.NM_CLIENTE, 
       COT_CLIENTE.NM_ABREVIADO, 
       COT_POSICAO_NOTA_HISTORICO.CD_FUNDO, 
       COT_TIPO_FUNDO.DS_TIPO_FUNDO, 
       ISNULL( SUM( COT_POSICAO_NOTA_HISTORICO.VL_CORRIGIDO ), CONVERT( FLOAT, 0 ) ) VL_CORRIGIDO, 
       ISNULL( SUM( COT_POSICAO_NOTA_HISTORICO.QT_COTAS ), CONVERT( FLOAT, 0 ) ) QT_COTAS
  FROM COT_FUNDO, 
       COT_CLIENTE, 
       COT_POSICAO_NOTA_HISTORICO
       INNER JOIN COT_MOVIMENTO 
          ON  COT_POSICAO_NOTA_HISTORICO.ID_NOTA = COT_MOVIMENTO.ID_NOTA,
       COT_FUNDO_PARAMETRO, 
       COT_TIPO_FUNDO 
 WHERE ( COT_POSICAO_NOTA_HISTORICO.DT_POSICAO =  @Data01   ) AND 
       ( COT_POSICAO_NOTA_HISTORICO.CD_FUNDO IN (  @Fundo   ) ) AND 
       ( COT_FUNDO.CD_CLIENTE = COT_CLIENTE.CD_CLIENTE ) AND 
       ( COT_FUNDO.CD_FUNDO = COT_POSICAO_NOTA_HISTORICO.CD_FUNDO ) AND 
       ( COT_POSICAO_NOTA_HISTORICO.DT_POSICAO BETWEEN COT_FUNDO_PARAMETRO.DT_INICIO_VALIDADE AND COT_FUNDO_PARAMETRO.DT_FIM_VALIDADE ) AND 
       ( COT_POSICAO_NOTA_HISTORICO.CD_FUNDO = COT_FUNDO_PARAMETRO.CD_FUNDO ) AND 
       ( COT_FUNDO_PARAMETRO.CD_TIPO_FUNDO = COT_TIPO_FUNDO.CD_TIPO_FUNDO ) AND 
       ( COT_MOVIMENTO.DT_LIQUIDACAO_FISICA <=  @Data01   ) AND
       ( EXISTS ( SELECT COTV_ACESSO_FUNDO_sub.CD_FUNDO 
                    FROM COTV_ACESSO_FUNDO COTV_ACESSO_FUNDO_sub 
                   WHERE ( COTV_ACESSO_FUNDO_sub.DS_LOGIN = 'I500422' ) AND 
                         ( COTV_ACESSO_FUNDO_sub.CD_FUNDO = COT_FUNDO.CD_FUNDO ) ) ) AND 
       ( COT_POSICAO_NOTA_HISTORICO.CD_COTISTA NOT IN ( SELECT ISNULL( COT_FUNDO_PARAMETRO_sub.CD_COTISTA, '' )
                                                          FROM COT_FUNDO_PARAMETRO COT_FUNDO_PARAMETRO_sub,   
                                                               COT_TIPO_FUNDO COT_TIPO_FUNDO_sub 
                                                         WHERE (  @Data01   BETWEEN COT_FUNDO_PARAMETRO_sub.DT_INICIO_VALIDADE AND COT_FUNDO_PARAMETRO_sub.DT_FIM_VALIDADE ) and  
                                                               ( COT_TIPO_FUNDO_sub.CD_TIPO_FUNDO = COT_FUNDO_PARAMETRO_sub.CD_TIPO_FUNDO ) and  
                                                               ( COT_TIPO_FUNDO_sub.IC_SN_FAQ = 'N' ) ) )
 GROUP BY COT_POSICAO_NOTA_HISTORICO.CD_FUNDO, 
       COT_CLIENTE.NM_ABREVIADO, 
       COT_CLIENTE.NM_CLIENTE, 
       COT_TIPO_FUNDO.DS_TIPO_FUNDO
 
UNION ALL 
 
SELECT COT_CLIENTE.NM_CLIENTE, 
       COT_CLIENTE.NM_ABREVIADO, 
       COT_MOVIMENTO.CD_FUNDO, 
       COT_TIPO_FUNDO.DS_TIPO_FUNDO, 
       ISNULL( SUM( COT_RESGATE_PROVISORIO.VL_CORRIGIDO ), CONVERT( FLOAT, 0 ) ) VL_CORRIGIDO, 
       ISNULL( SUM( COT_RESGATE_PROVISORIO.QT_COTAS ), CONVERT( FLOAT, 0 ) ) QT_COTAS
  FROM COT_MOVIMENTO, 
       COT_FUNDO, 
       COT_CLIENTE, 
       COT_RESGATE_PROVISORIO, 
       COT_FUNDO_PARAMETRO, 
       COT_TIPO_FUNDO 
 WHERE ( COT_RESGATE_PROVISORIO.DT_POSICAO =  @Data01   ) AND 
       ( COT_MOVIMENTO.CD_FUNDO IN (  @Fundo   ) ) AND 
       ( COT_RESGATE_PROVISORIO.ID_NOTA = COT_MOVIMENTO.ID_NOTA ) AND 
       ( COT_MOVIMENTO.CD_PADRAO <> 'V' ) AND 
       ( COT_MOVIMENTO.CD_FUNDO = COT_FUNDO.CD_FUNDO ) AND 
       ( COT_FUNDO.CD_CLIENTE = COT_CLIENTE.CD_CLIENTE ) AND 
       ( COT_RESGATE_PROVISORIO.DT_POSICAO BETWEEN COT_FUNDO_PARAMETRO.DT_INICIO_VALIDADE AND COT_FUNDO_PARAMETRO.DT_FIM_VALIDADE ) AND 
       ( COT_MOVIMENTO.CD_FUNDO = COT_FUNDO_PARAMETRO.CD_FUNDO ) AND 
       ( COT_FUNDO_PARAMETRO.CD_TIPO_FUNDO = COT_TIPO_FUNDO.CD_TIPO_FUNDO ) AND 
       ( EXISTS ( SELECT COTV_ACESSO_FUNDO_sub.CD_FUNDO 
                    FROM COTV_ACESSO_FUNDO COTV_ACESSO_FUNDO_sub 
                   WHERE ( COTV_ACESSO_FUNDO_sub.DS_LOGIN = 'I500422' ) AND 
                         ( COTV_ACESSO_FUNDO_sub.CD_FUNDO = COT_FUNDO.CD_FUNDO ) ) ) AND 
       ( COT_MOVIMENTO.CD_COTISTA NOT IN ( SELECT ISNULL( COT_FUNDO_PARAMETRO_sub.CD_COTISTA , '' )
                                             FROM COT_FUNDO_PARAMETRO COT_FUNDO_PARAMETRO_sub,   
                                                  COT_TIPO_FUNDO COT_TIPO_FUNDO_sub 
                                            WHERE (  @Data01   BETWEEN COT_FUNDO_PARAMETRO_sub.DT_INICIO_VALIDADE AND COT_FUNDO_PARAMETRO_sub.DT_FIM_VALIDADE ) and  
                                                  ( COT_TIPO_FUNDO_sub.CD_TIPO_FUNDO = COT_FUNDO_PARAMETRO_sub.CD_TIPO_FUNDO ) and  
                                                  ( COT_TIPO_FUNDO_sub.IC_SN_FAQ = 'N' ) ) )
 GROUP BY COT_MOVIMENTO.CD_FUNDO, 
       COT_CLIENTE.NM_ABREVIADO, 
       COT_CLIENTE.NM_CLIENTE, 
       COT_TIPO_FUNDO.DS_TIPO_FUNDO

